rust:
#  repo: "file:///home/jaggar/Code/matrix-rust-sdk"
  repo: "https://github.com/GigiaJ/matrix-rust-sdk"
  ref: "HEAD"
  manifestPath: bindings/matrix-sdk-ffi/Cargo.toml

web:
  workspace: true
  manifestPath: rust_modules/matrix-rust-sdk/bindings/wasm/Cargo.toml
  features: ["native-tls", "js", "indexeddb"]
  defaultFeatures: false
