"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports["default"] = exports.TimelineReadReceiptTracking = exports.TimelineEventShieldStateCode = exports.TimelineEventFocusThreadMode_Tags = exports.TimelineEventFocusThreadMode = exports.ThreadListPaginationState_Tags = exports.ThreadListPaginationState = exports.SpaceRoomListPaginationState_Tags = exports.SpaceRoomListPaginationState = exports.RoomPinnedEventsChange = exports.LatestEventValueLocalState = exports.EventItemOrigin = void 0;
var wasmBundle = _interopRequireWildcard(require("./wasm-bindgen/index.js"));
var _uniffiBindgenReactNative = require("uniffi-bindgen-react-native");
var _process;
function _interopRequireWildcard(e, t) { if ("function" == typeof WeakMap) var r = new WeakMap(), n = new WeakMap(); return (_interopRequireWildcard = function _interopRequireWildcard(e, t) { if (!t && e && e.__esModule) return e; var o, i, f = { __proto__: null, "default": e }; if (null === e || "object" != _typeof(e) && "function" != typeof e) return f; if (o = t ? n : r) { if (o.has(e)) return o.get(e); o.set(e, f); } for (var _t in e) "default" !== _t && {}.hasOwnProperty.call(e, _t) && ((i = (o = Object.defineProperty) && Object.getOwnPropertyDescriptor(e, _t)) && (i.get || i.set) ? o(f, _t, i) : f[_t] = e[_t]); return f; })(e, t); }
function _defineProperty(e, r, t) { return (r = _toPropertyKey(r)) in e ? Object.defineProperty(e, r, { value: t, enumerable: !0, configurable: !0, writable: !0 }) : e[r] = t, e; }
function _classCallCheck(a, n) { if (!(a instanceof n)) throw new TypeError("Cannot call a class as a function"); }
function _defineProperties(e, r) { for (var t = 0; t < r.length; t++) { var o = r[t]; o.enumerable = o.enumerable || !1, o.configurable = !0, "value" in o && (o.writable = !0), Object.defineProperty(e, _toPropertyKey(o.key), o); } }
function _createClass(e, r, t) { return r && _defineProperties(e.prototype, r), t && _defineProperties(e, t), Object.defineProperty(e, "prototype", { writable: !1 }), e; }
function _toPropertyKey(t) { var i = _toPrimitive(t, "string"); return "symbol" == _typeof(i) ? i : i + ""; }
function _toPrimitive(t, r) { if ("object" != _typeof(t) || !t) return t; var e = t[Symbol.toPrimitive]; if (void 0 !== e) { var i = e.call(t, r || "default"); if ("object" != _typeof(i)) return i; throw new TypeError("@@toPrimitive must return a primitive value."); } return ("string" === r ? String : Number)(t); }
function _callSuper(t, o, e) { return o = _getPrototypeOf(o), _possibleConstructorReturn(t, _isNativeReflectConstruct() ? Reflect.construct(o, e || [], _getPrototypeOf(t).constructor) : o.apply(t, e)); }
function _possibleConstructorReturn(t, e) { if (e && ("object" == _typeof(e) || "function" == typeof e)) return e; if (void 0 !== e) throw new TypeError("Derived constructors may only return object or undefined"); return _assertThisInitialized(t); }
function _assertThisInitialized(e) { if (void 0 === e) throw new ReferenceError("this hasn't been initialised - super() hasn't been called"); return e; }
function _isNativeReflectConstruct() { try { var t = !Boolean.prototype.valueOf.call(Reflect.construct(Boolean, [], function () {})); } catch (t) {} return (_isNativeReflectConstruct = function _isNativeReflectConstruct() { return !!t; })(); }
function _getPrototypeOf(t) { return _getPrototypeOf = Object.setPrototypeOf ? Object.getPrototypeOf.bind() : function (t) { return t.__proto__ || Object.getPrototypeOf(t); }, _getPrototypeOf(t); }
function _inherits(t, e) { if ("function" != typeof e && null !== e) throw new TypeError("Super expression must either be null or a function"); t.prototype = Object.create(e && e.prototype, { constructor: { value: t, writable: !0, configurable: !0 } }), Object.defineProperty(t, "prototype", { writable: !1 }), e && _setPrototypeOf(t, e); }
function _setPrototypeOf(t, e) { return _setPrototypeOf = Object.setPrototypeOf ? Object.setPrototypeOf.bind() : function (t, e) { return t.__proto__ = e, t; }, _setPrototypeOf(t, e); }
function _typeof(o) { "@babel/helpers - typeof"; return _typeof = "function" == typeof Symbol && "symbol" == typeof Symbol.iterator ? function (o) { return typeof o; } : function (o) { return o && "function" == typeof Symbol && o.constructor === Symbol && o !== Symbol.prototype ? "symbol" : typeof o; }, _typeof(o); } // This file was autogenerated by some hot garbage in the `uniffi-bindgen-react-native` crate.
// Trust me, you don't want to mess with it!
/* tslint:disable */ /* eslint-disable */ // @ts-nocheck
// Get converters from the other files, if any.
var nativeModule = function nativeModule() {
  return wasmBundle;
};
var uniffiCaller = new _uniffiBindgenReactNative.UniffiRustCaller(function () {
  return new wasmBundle.RustCallStatus();
});
var uniffiIsDebug =
// @ts-ignore -- The process global might not be defined
(typeof process === "undefined" ? "undefined" : _typeof(process)) !== "object" ||
// @ts-ignore -- The process global might not be defined
((_process = process) === null || _process === void 0 || (_process = _process.env) === null || _process === void 0 ? void 0 : _process.NODE_ENV) !== "production" || false;
// Public interface members begin here.

var stringConverter = function () {
  var encoder = new TextEncoder();
  var decoder = new TextDecoder();
  return {
    stringToBytes: function stringToBytes(s) {
      return encoder.encode(s);
    },
    bytesToString: function bytesToString(ab) {
      return decoder.decode(ab);
    },
    stringByteLength: function stringByteLength(s) {
      return encoder.encode(s).byteLength;
    }
  };
}();
var FfiConverterString = (0, _uniffiBindgenReactNative.uniffiCreateFfiConverterString)(stringConverter);

/**
 * Where this event came.
 */
var EventItemOrigin = exports.EventItemOrigin = /*#__PURE__*/function (EventItemOrigin) {
  /**
   * The event was created locally.
   */
  EventItemOrigin[EventItemOrigin["Local"] = 0] = "Local";
  /**
   * The event came from a sync response.
   */
  EventItemOrigin[EventItemOrigin["Sync"] = 1] = "Sync";
  /**
   * The event came from pagination.
   */
  EventItemOrigin[EventItemOrigin["Pagination"] = 2] = "Pagination";
  /**
   * The event came from a cache.
   */
  EventItemOrigin[EventItemOrigin["Cache"] = 3] = "Cache";
  return EventItemOrigin;
}({});
var FfiConverterTypeEventItemOrigin = function () {
  var ordinalConverter = _uniffiBindgenReactNative.FfiConverterInt32;
  var FFIConverter = /*#__PURE__*/function (_AbstractFfiConverter) {
    function FFIConverter() {
      _classCallCheck(this, FFIConverter);
      return _callSuper(this, FFIConverter, arguments);
    }
    _inherits(FFIConverter, _AbstractFfiConverter);
    return _createClass(FFIConverter, [{
      key: "read",
      value: function read(from) {
        switch (ordinalConverter.read(from)) {
          case 1:
            return EventItemOrigin.Local;
          case 2:
            return EventItemOrigin.Sync;
          case 3:
            return EventItemOrigin.Pagination;
          case 4:
            return EventItemOrigin.Cache;
          default:
            throw new _uniffiBindgenReactNative.UniffiInternalError.UnexpectedEnumCase();
        }
      }
    }, {
      key: "write",
      value: function write(value, into) {
        switch (value) {
          case EventItemOrigin.Local:
            return ordinalConverter.write(1, into);
          case EventItemOrigin.Sync:
            return ordinalConverter.write(2, into);
          case EventItemOrigin.Pagination:
            return ordinalConverter.write(3, into);
          case EventItemOrigin.Cache:
            return ordinalConverter.write(4, into);
        }
      }
    }, {
      key: "allocationSize",
      value: function allocationSize(value) {
        return ordinalConverter.allocationSize(0);
      }
    }]);
  }(_uniffiBindgenReactNative.AbstractFfiConverterByteArray);
  return new FFIConverter();
}();
var LatestEventValueLocalState = exports.LatestEventValueLocalState = /*#__PURE__*/function (LatestEventValueLocalState) {
  LatestEventValueLocalState[LatestEventValueLocalState["IsSending"] = 0] = "IsSending";
  LatestEventValueLocalState[LatestEventValueLocalState["HasBeenSent"] = 1] = "HasBeenSent";
  LatestEventValueLocalState[LatestEventValueLocalState["CannotBeSent"] = 2] = "CannotBeSent";
  return LatestEventValueLocalState;
}({});
var FfiConverterTypeLatestEventValueLocalState = function () {
  var ordinalConverter = _uniffiBindgenReactNative.FfiConverterInt32;
  var FFIConverter = /*#__PURE__*/function (_AbstractFfiConverter2) {
    function FFIConverter() {
      _classCallCheck(this, FFIConverter);
      return _callSuper(this, FFIConverter, arguments);
    }
    _inherits(FFIConverter, _AbstractFfiConverter2);
    return _createClass(FFIConverter, [{
      key: "read",
      value: function read(from) {
        switch (ordinalConverter.read(from)) {
          case 1:
            return LatestEventValueLocalState.IsSending;
          case 2:
            return LatestEventValueLocalState.HasBeenSent;
          case 3:
            return LatestEventValueLocalState.CannotBeSent;
          default:
            throw new _uniffiBindgenReactNative.UniffiInternalError.UnexpectedEnumCase();
        }
      }
    }, {
      key: "write",
      value: function write(value, into) {
        switch (value) {
          case LatestEventValueLocalState.IsSending:
            return ordinalConverter.write(1, into);
          case LatestEventValueLocalState.HasBeenSent:
            return ordinalConverter.write(2, into);
          case LatestEventValueLocalState.CannotBeSent:
            return ordinalConverter.write(3, into);
        }
      }
    }, {
      key: "allocationSize",
      value: function allocationSize(value) {
        return ordinalConverter.allocationSize(0);
      }
    }]);
  }(_uniffiBindgenReactNative.AbstractFfiConverterByteArray);
  return new FFIConverter();
}();

/**
 * The type of change between the previous and current pinned events.
 */
var RoomPinnedEventsChange = exports.RoomPinnedEventsChange = /*#__PURE__*/function (RoomPinnedEventsChange) {
  /**
   * Only new event ids were added.
   */
  RoomPinnedEventsChange[RoomPinnedEventsChange["Added"] = 0] = "Added";
  /**
   * Only event ids were removed.
   */
  RoomPinnedEventsChange[RoomPinnedEventsChange["Removed"] = 1] = "Removed";
  /**
   * Some change other than only adding or only removing ids happened.
   */
  RoomPinnedEventsChange[RoomPinnedEventsChange["Changed"] = 2] = "Changed";
  return RoomPinnedEventsChange;
}({});
var FfiConverterTypeRoomPinnedEventsChange = function () {
  var ordinalConverter = _uniffiBindgenReactNative.FfiConverterInt32;
  var FFIConverter = /*#__PURE__*/function (_AbstractFfiConverter3) {
    function FFIConverter() {
      _classCallCheck(this, FFIConverter);
      return _callSuper(this, FFIConverter, arguments);
    }
    _inherits(FFIConverter, _AbstractFfiConverter3);
    return _createClass(FFIConverter, [{
      key: "read",
      value: function read(from) {
        switch (ordinalConverter.read(from)) {
          case 1:
            return RoomPinnedEventsChange.Added;
          case 2:
            return RoomPinnedEventsChange.Removed;
          case 3:
            return RoomPinnedEventsChange.Changed;
          default:
            throw new _uniffiBindgenReactNative.UniffiInternalError.UnexpectedEnumCase();
        }
      }
    }, {
      key: "write",
      value: function write(value, into) {
        switch (value) {
          case RoomPinnedEventsChange.Added:
            return ordinalConverter.write(1, into);
          case RoomPinnedEventsChange.Removed:
            return ordinalConverter.write(2, into);
          case RoomPinnedEventsChange.Changed:
            return ordinalConverter.write(3, into);
        }
      }
    }, {
      key: "allocationSize",
      value: function allocationSize(value) {
        return ordinalConverter.allocationSize(0);
      }
    }]);
  }(_uniffiBindgenReactNative.AbstractFfiConverterByteArray);
  return new FFIConverter();
}();

// Enum: SpaceRoomListPaginationState
var SpaceRoomListPaginationState_Tags = exports.SpaceRoomListPaginationState_Tags = /*#__PURE__*/function (SpaceRoomListPaginationState_Tags) {
  SpaceRoomListPaginationState_Tags["Idle"] = "Idle";
  SpaceRoomListPaginationState_Tags["Loading"] = "Loading";
  return SpaceRoomListPaginationState_Tags;
}({});
var SpaceRoomListPaginationState = exports.SpaceRoomListPaginationState = function () {
  var Idle_ = /*#__PURE__*/function (_UniffiEnum) {
    function Idle_(inner) {
      var _this;
      _classCallCheck(this, Idle_);
      _this = _callSuper(this, Idle_, ["SpaceRoomListPaginationState", "Idle"]);
      /**
       * @private
       * This field is private and should not be used, use `tag` instead.
       */
      _defineProperty(_this, _uniffiBindgenReactNative.uniffiTypeNameSymbol, "SpaceRoomListPaginationState");
      _defineProperty(_this, "tag", SpaceRoomListPaginationState_Tags.Idle);
      _defineProperty(_this, "inner", void 0);
      _this.inner = Object.freeze(inner);
      return _this;
    }
    _inherits(Idle_, _UniffiEnum);
    return _createClass(Idle_, null, [{
      key: "new",
      value: function _new(inner) {
        return new Idle_(inner);
      }
    }, {
      key: "instanceOf",
      value: function instanceOf(obj) {
        return obj.tag === SpaceRoomListPaginationState_Tags.Idle;
      }
    }]);
  }(_uniffiBindgenReactNative.UniffiEnum);
  var Loading_ = /*#__PURE__*/function (_UniffiEnum2) {
    function Loading_() {
      var _this2;
      _classCallCheck(this, Loading_);
      _this2 = _callSuper(this, Loading_, ["SpaceRoomListPaginationState", "Loading"]);
      /**
       * @private
       * This field is private and should not be used, use `tag` instead.
       */
      _defineProperty(_this2, _uniffiBindgenReactNative.uniffiTypeNameSymbol, "SpaceRoomListPaginationState");
      _defineProperty(_this2, "tag", SpaceRoomListPaginationState_Tags.Loading);
      return _this2;
    }
    _inherits(Loading_, _UniffiEnum2);
    return _createClass(Loading_, null, [{
      key: "new",
      value: function _new() {
        return new Loading_();
      }
    }, {
      key: "instanceOf",
      value: function instanceOf(obj) {
        return obj.tag === SpaceRoomListPaginationState_Tags.Loading;
      }
    }]);
  }(_uniffiBindgenReactNative.UniffiEnum);
  function instanceOf(obj) {
    return obj[_uniffiBindgenReactNative.uniffiTypeNameSymbol] === "SpaceRoomListPaginationState";
  }
  return Object.freeze({
    instanceOf: instanceOf,
    Idle: Idle_,
    Loading: Loading_
  });
}();
// FfiConverter for enum SpaceRoomListPaginationState
var FfiConverterTypeSpaceRoomListPaginationState = function () {
  var ordinalConverter = _uniffiBindgenReactNative.FfiConverterInt32;
  var FFIConverter = /*#__PURE__*/function (_AbstractFfiConverter4) {
    function FFIConverter() {
      _classCallCheck(this, FFIConverter);
      return _callSuper(this, FFIConverter, arguments);
    }
    _inherits(FFIConverter, _AbstractFfiConverter4);
    return _createClass(FFIConverter, [{
      key: "read",
      value: function read(from) {
        switch (ordinalConverter.read(from)) {
          case 1:
            return new SpaceRoomListPaginationState.Idle({
              endReached: _uniffiBindgenReactNative.FfiConverterBool.read(from)
            });
          case 2:
            return new SpaceRoomListPaginationState.Loading();
          default:
            throw new _uniffiBindgenReactNative.UniffiInternalError.UnexpectedEnumCase();
        }
      }
    }, {
      key: "write",
      value: function write(value, into) {
        switch (value.tag) {
          case SpaceRoomListPaginationState_Tags.Idle:
            {
              ordinalConverter.write(1, into);
              var inner = value.inner;
              _uniffiBindgenReactNative.FfiConverterBool.write(inner.endReached, into);
              return;
            }
          case SpaceRoomListPaginationState_Tags.Loading:
            {
              ordinalConverter.write(2, into);
              return;
            }
          default:
            // Throwing from here means that SpaceRoomListPaginationState_Tags hasn't matched an ordinal.
            throw new _uniffiBindgenReactNative.UniffiInternalError.UnexpectedEnumCase();
        }
      }
    }, {
      key: "allocationSize",
      value: function allocationSize(value) {
        switch (value.tag) {
          case SpaceRoomListPaginationState_Tags.Idle:
            {
              var inner = value.inner;
              var size = ordinalConverter.allocationSize(1);
              size += _uniffiBindgenReactNative.FfiConverterBool.allocationSize(inner.endReached);
              return size;
            }
          case SpaceRoomListPaginationState_Tags.Loading:
            {
              return ordinalConverter.allocationSize(2);
            }
          default:
            throw new _uniffiBindgenReactNative.UniffiInternalError.UnexpectedEnumCase();
        }
      }
    }]);
  }(_uniffiBindgenReactNative.AbstractFfiConverterByteArray);
  return new FFIConverter();
}();

// Enum: ThreadListPaginationState
var ThreadListPaginationState_Tags = exports.ThreadListPaginationState_Tags = /*#__PURE__*/function (ThreadListPaginationState_Tags) {
  ThreadListPaginationState_Tags["Idle"] = "Idle";
  ThreadListPaginationState_Tags["Loading"] = "Loading";
  return ThreadListPaginationState_Tags;
}({});
/**
 * The pagination state of a [`ThreadListService`].
 */
var ThreadListPaginationState = exports.ThreadListPaginationState = function () {
  /**
   * The list is idle (not currently loading).
   */
  var Idle_ = /*#__PURE__*/function (_UniffiEnum3) {
    function Idle_(inner) {
      var _this3;
      _classCallCheck(this, Idle_);
      _this3 = _callSuper(this, Idle_, ["ThreadListPaginationState", "Idle"]);
      /**
       * @private
       * This field is private and should not be used, use `tag` instead.
       */
      _defineProperty(_this3, _uniffiBindgenReactNative.uniffiTypeNameSymbol, "ThreadListPaginationState");
      _defineProperty(_this3, "tag", ThreadListPaginationState_Tags.Idle);
      _defineProperty(_this3, "inner", void 0);
      _this3.inner = Object.freeze(inner);
      return _this3;
    }
    _inherits(Idle_, _UniffiEnum3);
    return _createClass(Idle_, null, [{
      key: "new",
      value: function _new(inner) {
        return new Idle_(inner);
      }
    }, {
      key: "instanceOf",
      value: function instanceOf(obj) {
        return obj.tag === ThreadListPaginationState_Tags.Idle;
      }
    }]);
  }(_uniffiBindgenReactNative.UniffiEnum);
  /**
   * The list is currently loading the next page.
   */
  var Loading_ = /*#__PURE__*/function (_UniffiEnum4) {
    function Loading_() {
      var _this4;
      _classCallCheck(this, Loading_);
      _this4 = _callSuper(this, Loading_, ["ThreadListPaginationState", "Loading"]);
      /**
       * @private
       * This field is private and should not be used, use `tag` instead.
       */
      _defineProperty(_this4, _uniffiBindgenReactNative.uniffiTypeNameSymbol, "ThreadListPaginationState");
      _defineProperty(_this4, "tag", ThreadListPaginationState_Tags.Loading);
      return _this4;
    }
    _inherits(Loading_, _UniffiEnum4);
    return _createClass(Loading_, null, [{
      key: "new",
      value: function _new() {
        return new Loading_();
      }
    }, {
      key: "instanceOf",
      value: function instanceOf(obj) {
        return obj.tag === ThreadListPaginationState_Tags.Loading;
      }
    }]);
  }(_uniffiBindgenReactNative.UniffiEnum);
  function instanceOf(obj) {
    return obj[_uniffiBindgenReactNative.uniffiTypeNameSymbol] === "ThreadListPaginationState";
  }
  return Object.freeze({
    instanceOf: instanceOf,
    Idle: Idle_,
    Loading: Loading_
  });
}();

/**
 * The pagination state of a [`ThreadListService`].
 */

// FfiConverter for enum ThreadListPaginationState
var FfiConverterTypeThreadListPaginationState = function () {
  var ordinalConverter = _uniffiBindgenReactNative.FfiConverterInt32;
  var FFIConverter = /*#__PURE__*/function (_AbstractFfiConverter5) {
    function FFIConverter() {
      _classCallCheck(this, FFIConverter);
      return _callSuper(this, FFIConverter, arguments);
    }
    _inherits(FFIConverter, _AbstractFfiConverter5);
    return _createClass(FFIConverter, [{
      key: "read",
      value: function read(from) {
        switch (ordinalConverter.read(from)) {
          case 1:
            return new ThreadListPaginationState.Idle({
              endReached: _uniffiBindgenReactNative.FfiConverterBool.read(from)
            });
          case 2:
            return new ThreadListPaginationState.Loading();
          default:
            throw new _uniffiBindgenReactNative.UniffiInternalError.UnexpectedEnumCase();
        }
      }
    }, {
      key: "write",
      value: function write(value, into) {
        switch (value.tag) {
          case ThreadListPaginationState_Tags.Idle:
            {
              ordinalConverter.write(1, into);
              var inner = value.inner;
              _uniffiBindgenReactNative.FfiConverterBool.write(inner.endReached, into);
              return;
            }
          case ThreadListPaginationState_Tags.Loading:
            {
              ordinalConverter.write(2, into);
              return;
            }
          default:
            // Throwing from here means that ThreadListPaginationState_Tags hasn't matched an ordinal.
            throw new _uniffiBindgenReactNative.UniffiInternalError.UnexpectedEnumCase();
        }
      }
    }, {
      key: "allocationSize",
      value: function allocationSize(value) {
        switch (value.tag) {
          case ThreadListPaginationState_Tags.Idle:
            {
              var inner = value.inner;
              var size = ordinalConverter.allocationSize(1);
              size += _uniffiBindgenReactNative.FfiConverterBool.allocationSize(inner.endReached);
              return size;
            }
          case ThreadListPaginationState_Tags.Loading:
            {
              return ordinalConverter.allocationSize(2);
            }
          default:
            throw new _uniffiBindgenReactNative.UniffiInternalError.UnexpectedEnumCase();
        }
      }
    }]);
  }(_uniffiBindgenReactNative.AbstractFfiConverterByteArray);
  return new FFIConverter();
}();

// Enum: TimelineEventFocusThreadMode
var TimelineEventFocusThreadMode_Tags = exports.TimelineEventFocusThreadMode_Tags = /*#__PURE__*/function (TimelineEventFocusThreadMode_Tags) {
  TimelineEventFocusThreadMode_Tags["ForceThread"] = "ForceThread";
  TimelineEventFocusThreadMode_Tags["Automatic"] = "Automatic";
  return TimelineEventFocusThreadMode_Tags;
}({});
/**
 * Options for controlling the behaviour of [`TimelineFocus::Event`]
 * for threaded events.
 */
var TimelineEventFocusThreadMode = exports.TimelineEventFocusThreadMode = function () {
  /**
   * Force the timeline into threaded mode.
   *
   * When the focused event is part of a thread, the timeline will be focused
   * on that thread's root. Otherwise, the timeline will treat the target
   * event itself as the thread root. Threaded events will never be
   * hidden.
   */
  var ForceThread_ = /*#__PURE__*/function (_UniffiEnum5) {
    function ForceThread_() {
      var _this5;
      _classCallCheck(this, ForceThread_);
      _this5 = _callSuper(this, ForceThread_, ["TimelineEventFocusThreadMode", "ForceThread"]);
      /**
       * @private
       * This field is private and should not be used, use `tag` instead.
       */
      _defineProperty(_this5, _uniffiBindgenReactNative.uniffiTypeNameSymbol, "TimelineEventFocusThreadMode");
      _defineProperty(_this5, "tag", TimelineEventFocusThreadMode_Tags.ForceThread);
      return _this5;
    }
    _inherits(ForceThread_, _UniffiEnum5);
    return _createClass(ForceThread_, null, [{
      key: "new",
      value: function _new() {
        return new ForceThread_();
      }
    }, {
      key: "instanceOf",
      value: function instanceOf(obj) {
        return obj.tag === TimelineEventFocusThreadMode_Tags.ForceThread;
      }
    }]);
  }(_uniffiBindgenReactNative.UniffiEnum);
  /**
   * Automatically determine if the target event is part of a thread or not.
   *
   * If the event is part of a thread, the timeline
   * will be filtered to on-thread events.
   */
  var Automatic_ = /*#__PURE__*/function (_UniffiEnum6) {
    function Automatic_(inner) {
      var _this6;
      _classCallCheck(this, Automatic_);
      _this6 = _callSuper(this, Automatic_, ["TimelineEventFocusThreadMode", "Automatic"]);
      /**
       * @private
       * This field is private and should not be used, use `tag` instead.
       */
      _defineProperty(_this6, _uniffiBindgenReactNative.uniffiTypeNameSymbol, "TimelineEventFocusThreadMode");
      _defineProperty(_this6, "tag", TimelineEventFocusThreadMode_Tags.Automatic);
      _defineProperty(_this6, "inner", void 0);
      _this6.inner = Object.freeze(inner);
      return _this6;
    }
    _inherits(Automatic_, _UniffiEnum6);
    return _createClass(Automatic_, null, [{
      key: "new",
      value: function _new(inner) {
        return new Automatic_(inner);
      }
    }, {
      key: "instanceOf",
      value: function instanceOf(obj) {
        return obj.tag === TimelineEventFocusThreadMode_Tags.Automatic;
      }
    }]);
  }(_uniffiBindgenReactNative.UniffiEnum);
  function instanceOf(obj) {
    return obj[_uniffiBindgenReactNative.uniffiTypeNameSymbol] === "TimelineEventFocusThreadMode";
  }
  return Object.freeze({
    instanceOf: instanceOf,
    ForceThread: ForceThread_,
    Automatic: Automatic_
  });
}();

/**
 * Options for controlling the behaviour of [`TimelineFocus::Event`]
 * for threaded events.
 */

// FfiConverter for enum TimelineEventFocusThreadMode
var FfiConverterTypeTimelineEventFocusThreadMode = function () {
  var ordinalConverter = _uniffiBindgenReactNative.FfiConverterInt32;
  var FFIConverter = /*#__PURE__*/function (_AbstractFfiConverter6) {
    function FFIConverter() {
      _classCallCheck(this, FFIConverter);
      return _callSuper(this, FFIConverter, arguments);
    }
    _inherits(FFIConverter, _AbstractFfiConverter6);
    return _createClass(FFIConverter, [{
      key: "read",
      value: function read(from) {
        switch (ordinalConverter.read(from)) {
          case 1:
            return new TimelineEventFocusThreadMode.ForceThread();
          case 2:
            return new TimelineEventFocusThreadMode.Automatic({
              hideThreadedEvents: _uniffiBindgenReactNative.FfiConverterBool.read(from)
            });
          default:
            throw new _uniffiBindgenReactNative.UniffiInternalError.UnexpectedEnumCase();
        }
      }
    }, {
      key: "write",
      value: function write(value, into) {
        switch (value.tag) {
          case TimelineEventFocusThreadMode_Tags.ForceThread:
            {
              ordinalConverter.write(1, into);
              return;
            }
          case TimelineEventFocusThreadMode_Tags.Automatic:
            {
              ordinalConverter.write(2, into);
              var inner = value.inner;
              _uniffiBindgenReactNative.FfiConverterBool.write(inner.hideThreadedEvents, into);
              return;
            }
          default:
            // Throwing from here means that TimelineEventFocusThreadMode_Tags hasn't matched an ordinal.
            throw new _uniffiBindgenReactNative.UniffiInternalError.UnexpectedEnumCase();
        }
      }
    }, {
      key: "allocationSize",
      value: function allocationSize(value) {
        switch (value.tag) {
          case TimelineEventFocusThreadMode_Tags.ForceThread:
            {
              return ordinalConverter.allocationSize(1);
            }
          case TimelineEventFocusThreadMode_Tags.Automatic:
            {
              var inner = value.inner;
              var size = ordinalConverter.allocationSize(2);
              size += _uniffiBindgenReactNative.FfiConverterBool.allocationSize(inner.hideThreadedEvents);
              return size;
            }
          default:
            throw new _uniffiBindgenReactNative.UniffiInternalError.UnexpectedEnumCase();
        }
      }
    }]);
  }(_uniffiBindgenReactNative.AbstractFfiConverterByteArray);
  return new FFIConverter();
}();

/**
 * Extends [`ShieldStateCode`] to allow for a `SentInClear` code.
 */
var TimelineEventShieldStateCode = exports.TimelineEventShieldStateCode = /*#__PURE__*/function (TimelineEventShieldStateCode) {
  /**
   * Not enough information available to check the authenticity.
   */
  TimelineEventShieldStateCode[TimelineEventShieldStateCode["AuthenticityNotGuaranteed"] = 0] = "AuthenticityNotGuaranteed";
  /**
   * The sending device isn't yet known by the Client.
   */
  TimelineEventShieldStateCode[TimelineEventShieldStateCode["UnknownDevice"] = 1] = "UnknownDevice";
  /**
   * The sending device hasn't been verified by the sender.
   */
  TimelineEventShieldStateCode[TimelineEventShieldStateCode["UnsignedDevice"] = 2] = "UnsignedDevice";
  /**
   * The sender hasn't been verified by the Client's user.
   */
  TimelineEventShieldStateCode[TimelineEventShieldStateCode["UnverifiedIdentity"] = 3] = "UnverifiedIdentity";
  /**
   * The sender was previously verified but changed their identity.
   */
  TimelineEventShieldStateCode[TimelineEventShieldStateCode["VerificationViolation"] = 4] = "VerificationViolation";
  /**
   * The `sender` field on the event does not match the owner of the device
   * that established the Megolm session.
   */
  TimelineEventShieldStateCode[TimelineEventShieldStateCode["MismatchedSender"] = 5] = "MismatchedSender";
  /**
   * An unencrypted event in an encrypted room.
   */
  TimelineEventShieldStateCode[TimelineEventShieldStateCode["SentInClear"] = 6] = "SentInClear";
  return TimelineEventShieldStateCode;
}({});
var FfiConverterTypeTimelineEventShieldStateCode = function () {
  var ordinalConverter = _uniffiBindgenReactNative.FfiConverterInt32;
  var FFIConverter = /*#__PURE__*/function (_AbstractFfiConverter7) {
    function FFIConverter() {
      _classCallCheck(this, FFIConverter);
      return _callSuper(this, FFIConverter, arguments);
    }
    _inherits(FFIConverter, _AbstractFfiConverter7);
    return _createClass(FFIConverter, [{
      key: "read",
      value: function read(from) {
        switch (ordinalConverter.read(from)) {
          case 1:
            return TimelineEventShieldStateCode.AuthenticityNotGuaranteed;
          case 2:
            return TimelineEventShieldStateCode.UnknownDevice;
          case 3:
            return TimelineEventShieldStateCode.UnsignedDevice;
          case 4:
            return TimelineEventShieldStateCode.UnverifiedIdentity;
          case 5:
            return TimelineEventShieldStateCode.VerificationViolation;
          case 6:
            return TimelineEventShieldStateCode.MismatchedSender;
          case 7:
            return TimelineEventShieldStateCode.SentInClear;
          default:
            throw new _uniffiBindgenReactNative.UniffiInternalError.UnexpectedEnumCase();
        }
      }
    }, {
      key: "write",
      value: function write(value, into) {
        switch (value) {
          case TimelineEventShieldStateCode.AuthenticityNotGuaranteed:
            return ordinalConverter.write(1, into);
          case TimelineEventShieldStateCode.UnknownDevice:
            return ordinalConverter.write(2, into);
          case TimelineEventShieldStateCode.UnsignedDevice:
            return ordinalConverter.write(3, into);
          case TimelineEventShieldStateCode.UnverifiedIdentity:
            return ordinalConverter.write(4, into);
          case TimelineEventShieldStateCode.VerificationViolation:
            return ordinalConverter.write(5, into);
          case TimelineEventShieldStateCode.MismatchedSender:
            return ordinalConverter.write(6, into);
          case TimelineEventShieldStateCode.SentInClear:
            return ordinalConverter.write(7, into);
        }
      }
    }, {
      key: "allocationSize",
      value: function allocationSize(value) {
        return ordinalConverter.allocationSize(0);
      }
    }]);
  }(_uniffiBindgenReactNative.AbstractFfiConverterByteArray);
  return new FFIConverter();
}();

/**
 * The level of read receipt tracking for the timeline.
 */
var TimelineReadReceiptTracking = exports.TimelineReadReceiptTracking = /*#__PURE__*/function (TimelineReadReceiptTracking) {
  /**
   * Track read receipts for all events.
   */
  TimelineReadReceiptTracking[TimelineReadReceiptTracking["AllEvents"] = 0] = "AllEvents";
  /**
   * Track read receipts only for message-like events.
   */
  TimelineReadReceiptTracking[TimelineReadReceiptTracking["MessageLikeEvents"] = 1] = "MessageLikeEvents";
  /**
   * Disable read receipt tracking.
   */
  TimelineReadReceiptTracking[TimelineReadReceiptTracking["Disabled"] = 2] = "Disabled";
  return TimelineReadReceiptTracking;
}({});
var FfiConverterTypeTimelineReadReceiptTracking = function () {
  var ordinalConverter = _uniffiBindgenReactNative.FfiConverterInt32;
  var FFIConverter = /*#__PURE__*/function (_AbstractFfiConverter8) {
    function FFIConverter() {
      _classCallCheck(this, FFIConverter);
      return _callSuper(this, FFIConverter, arguments);
    }
    _inherits(FFIConverter, _AbstractFfiConverter8);
    return _createClass(FFIConverter, [{
      key: "read",
      value: function read(from) {
        switch (ordinalConverter.read(from)) {
          case 1:
            return TimelineReadReceiptTracking.AllEvents;
          case 2:
            return TimelineReadReceiptTracking.MessageLikeEvents;
          case 3:
            return TimelineReadReceiptTracking.Disabled;
          default:
            throw new _uniffiBindgenReactNative.UniffiInternalError.UnexpectedEnumCase();
        }
      }
    }, {
      key: "write",
      value: function write(value, into) {
        switch (value) {
          case TimelineReadReceiptTracking.AllEvents:
            return ordinalConverter.write(1, into);
          case TimelineReadReceiptTracking.MessageLikeEvents:
            return ordinalConverter.write(2, into);
          case TimelineReadReceiptTracking.Disabled:
            return ordinalConverter.write(3, into);
        }
      }
    }, {
      key: "allocationSize",
      value: function allocationSize(value) {
        return ordinalConverter.allocationSize(0);
      }
    }]);
  }(_uniffiBindgenReactNative.AbstractFfiConverterByteArray);
  return new FFIConverter();
}();

/**
 * This should be called before anything else.
 *
 * It is likely that this is being done for you by the library's `index.ts`.
 *
 * It checks versions of uniffi between when the Rust scaffolding was generated
 * and when the bindings were generated.
 *
 * It also initializes the machinery to enable Rust to talk back to Javascript.
 */
function uniffiEnsureInitialized() {
  // Get the bindings contract version from our ComponentInterface
  var bindingsContractVersion = 30;
  // Get the scaffolding contract version by calling the into the dylib
  var scaffoldingContractVersion = nativeModule().ubrn_ffi_matrix_sdk_ui_uniffi_contract_version();
  if (bindingsContractVersion !== scaffoldingContractVersion) {
    throw new _uniffiBindgenReactNative.UniffiInternalError.ContractVersionMismatch(scaffoldingContractVersion, bindingsContractVersion);
  }
}
var _default = exports["default"] = Object.freeze({
  initialize: uniffiEnsureInitialized,
  converters: {
    FfiConverterTypeEventItemOrigin: FfiConverterTypeEventItemOrigin,
    FfiConverterTypeLatestEventValueLocalState: FfiConverterTypeLatestEventValueLocalState,
    FfiConverterTypeRoomPinnedEventsChange: FfiConverterTypeRoomPinnedEventsChange,
    FfiConverterTypeSpaceRoomListPaginationState: FfiConverterTypeSpaceRoomListPaginationState,
    FfiConverterTypeThreadListPaginationState: FfiConverterTypeThreadListPaginationState,
    FfiConverterTypeTimelineEventFocusThreadMode: FfiConverterTypeTimelineEventFocusThreadMode,
    FfiConverterTypeTimelineEventShieldStateCode: FfiConverterTypeTimelineEventShieldStateCode,
    FfiConverterTypeTimelineReadReceiptTracking: FfiConverterTypeTimelineReadReceiptTracking
  }
});