var _process;
function _defineProperty(e, r, t) { return (r = _toPropertyKey(r)) in e ? Object.defineProperty(e, r, { value: t, enumerable: !0, configurable: !0, writable: !0 }) : e[r] = t, e; }
function _classCallCheck(a, n) { if (!(a instanceof n)) throw new TypeError("Cannot call a class as a function"); }
function _defineProperties(e, r) { for (var t = 0; t < r.length; t++) { var o = r[t]; o.enumerable = o.enumerable || !1, o.configurable = !0, "value" in o && (o.writable = !0), Object.defineProperty(e, _toPropertyKey(o.key), o); } }
function _createClass(e, r, t) { return r && _defineProperties(e.prototype, r), t && _defineProperties(e, t), Object.defineProperty(e, "prototype", { writable: !1 }), e; }
function _toPropertyKey(t) { var i = _toPrimitive(t, "string"); return "symbol" == _typeof(i) ? i : i + ""; }
function _toPrimitive(t, r) { if ("object" != _typeof(t) || !t) return t; var e = t[Symbol.toPrimitive]; if (void 0 !== e) { var i = e.call(t, r || "default"); if ("object" != _typeof(i)) return i; throw new TypeError("@@toPrimitive must return a primitive value."); } return ("string" === r ? String : Number)(t); }
function _callSuper(t, o, e) { return o = _getPrototypeOf(o), _possibleConstructorReturn(t, _isNativeReflectConstruct() ? Reflect.construct(o, e || [], _getPrototypeOf(t).constructor) : o.apply(t, e)); }
function _possibleConstructorReturn(t, e) { if (e && ("object" == _typeof(e) || "function" == typeof e)) return e; if (void 0 !== e) throw new TypeError("Derived constructors may only return object or undefined"); return _assertThisInitialized(t); }
function _assertThisInitialized(e) { if (void 0 === e) throw new ReferenceError("this hasn't been initialised - super() hasn't been called"); return e; }
function _isNativeReflectConstruct() { try { var t = !Boolean.prototype.valueOf.call(Reflect.construct(Boolean, [], function () {})); } catch (t) {} return (_isNativeReflectConstruct = function _isNativeReflectConstruct() { return !!t; })(); }
function _getPrototypeOf(t) { return _getPrototypeOf = Object.setPrototypeOf ? Object.getPrototypeOf.bind() : function (t) { return t.__proto__ || Object.getPrototypeOf(t); }, _getPrototypeOf(t); }
function _inherits(t, e) { if ("function" != typeof e && null !== e) throw new TypeError("Super expression must either be null or a function"); t.prototype = Object.create(e && e.prototype, { constructor: { value: t, writable: !0, configurable: !0 } }), Object.defineProperty(t, "prototype", { writable: !1 }), e && _setPrototypeOf(t, e); }
function _setPrototypeOf(t, e) { return _setPrototypeOf = Object.setPrototypeOf ? Object.setPrototypeOf.bind() : function (t, e) { return t.__proto__ = e, t; }, _setPrototypeOf(t, e); }
function _typeof(o) { "@babel/helpers - typeof"; return _typeof = "function" == typeof Symbol && "symbol" == typeof Symbol.iterator ? function (o) { return typeof o; } : function (o) { return o && "function" == typeof Symbol && o.constructor === Symbol && o !== Symbol.prototype ? "symbol" : typeof o; }, _typeof(o); }
// This file was autogenerated by some hot garbage in the `uniffi-bindgen-react-native` crate.
// Trust me, you don't want to mess with it!
/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
import * as wasmBundle from "./wasm-bindgen/index.js";
import { AbstractFfiConverterByteArray, FfiConverterBool, FfiConverterInt32, UniffiEnum, UniffiInternalError, UniffiRustCaller, uniffiCreateFfiConverterString, uniffiTypeNameSymbol } from "uniffi-bindgen-react-native";
// Get converters from the other files, if any.
var nativeModule = function nativeModule() {
  return wasmBundle;
};
var uniffiCaller = new UniffiRustCaller(function () {
  return new wasmBundle.RustCallStatus();
});
var uniffiIsDebug =
// @ts-ignore -- The process global might not be defined
(typeof process === "undefined" ? "undefined" : _typeof(process)) !== "object" ||
// @ts-ignore -- The process global might not be defined
((_process = process) === null || _process === void 0 || (_process = _process.env) === null || _process === void 0 ? void 0 : _process.NODE_ENV) !== "production" || false;
// Public interface members begin here.
var stringConverter = function () {
  var encoder = new TextEncoder();
  var decoder = new TextDecoder();
  return {
    stringToBytes: function stringToBytes(s) {
      return encoder.encode(s);
    },
    bytesToString: function bytesToString(ab) {
      return decoder.decode(ab);
    },
    stringByteLength: function stringByteLength(s) {
      return encoder.encode(s).byteLength;
    }
  };
}();
var FfiConverterString = uniffiCreateFfiConverterString(stringConverter);
/**
 * Where this event came.
 */
export var EventItemOrigin;
(function (EventItemOrigin) {
  /**
   * The event was created locally.
   */
  EventItemOrigin[EventItemOrigin["Local"] = 0] = "Local";
  /**
   * The event came from a sync response.
   */
  EventItemOrigin[EventItemOrigin["Sync"] = 1] = "Sync";
  /**
   * The event came from pagination.
   */
  EventItemOrigin[EventItemOrigin["Pagination"] = 2] = "Pagination";
  /**
   * The event came from a cache.
   */
  EventItemOrigin[EventItemOrigin["Cache"] = 3] = "Cache";
})(EventItemOrigin || (EventItemOrigin = {}));
var FfiConverterTypeEventItemOrigin = function () {
  var ordinalConverter = FfiConverterInt32;
  var FFIConverter = /*#__PURE__*/function (_AbstractFfiConverter) {
    function FFIConverter() {
      _classCallCheck(this, FFIConverter);
      return _callSuper(this, FFIConverter, arguments);
    }
    _inherits(FFIConverter, _AbstractFfiConverter);
    return _createClass(FFIConverter, [{
      key: "read",
      value: function read(from) {
        switch (ordinalConverter.read(from)) {
          case 1:
            return EventItemOrigin.Local;
          case 2:
            return EventItemOrigin.Sync;
          case 3:
            return EventItemOrigin.Pagination;
          case 4:
            return EventItemOrigin.Cache;
          default:
            throw new UniffiInternalError.UnexpectedEnumCase();
        }
      }
    }, {
      key: "write",
      value: function write(value, into) {
        switch (value) {
          case EventItemOrigin.Local:
            return ordinalConverter.write(1, into);
          case EventItemOrigin.Sync:
            return ordinalConverter.write(2, into);
          case EventItemOrigin.Pagination:
            return ordinalConverter.write(3, into);
          case EventItemOrigin.Cache:
            return ordinalConverter.write(4, into);
        }
      }
    }, {
      key: "allocationSize",
      value: function allocationSize(value) {
        return ordinalConverter.allocationSize(0);
      }
    }]);
  }(AbstractFfiConverterByteArray);
  return new FFIConverter();
}();
/**
 * The type of change between the previous and current pinned events.
 */
export var RoomPinnedEventsChange;
(function (RoomPinnedEventsChange) {
  /**
   * Only new event ids were added.
   */
  RoomPinnedEventsChange[RoomPinnedEventsChange["Added"] = 0] = "Added";
  /**
   * Only event ids were removed.
   */
  RoomPinnedEventsChange[RoomPinnedEventsChange["Removed"] = 1] = "Removed";
  /**
   * Some change other than only adding or only removing ids happened.
   */
  RoomPinnedEventsChange[RoomPinnedEventsChange["Changed"] = 2] = "Changed";
})(RoomPinnedEventsChange || (RoomPinnedEventsChange = {}));
var FfiConverterTypeRoomPinnedEventsChange = function () {
  var ordinalConverter = FfiConverterInt32;
  var FFIConverter = /*#__PURE__*/function (_AbstractFfiConverter2) {
    function FFIConverter() {
      _classCallCheck(this, FFIConverter);
      return _callSuper(this, FFIConverter, arguments);
    }
    _inherits(FFIConverter, _AbstractFfiConverter2);
    return _createClass(FFIConverter, [{
      key: "read",
      value: function read(from) {
        switch (ordinalConverter.read(from)) {
          case 1:
            return RoomPinnedEventsChange.Added;
          case 2:
            return RoomPinnedEventsChange.Removed;
          case 3:
            return RoomPinnedEventsChange.Changed;
          default:
            throw new UniffiInternalError.UnexpectedEnumCase();
        }
      }
    }, {
      key: "write",
      value: function write(value, into) {
        switch (value) {
          case RoomPinnedEventsChange.Added:
            return ordinalConverter.write(1, into);
          case RoomPinnedEventsChange.Removed:
            return ordinalConverter.write(2, into);
          case RoomPinnedEventsChange.Changed:
            return ordinalConverter.write(3, into);
        }
      }
    }, {
      key: "allocationSize",
      value: function allocationSize(value) {
        return ordinalConverter.allocationSize(0);
      }
    }]);
  }(AbstractFfiConverterByteArray);
  return new FFIConverter();
}();
// Enum: SpaceRoomListPaginationState
export var SpaceRoomListPaginationState_Tags;
(function (SpaceRoomListPaginationState_Tags) {
  SpaceRoomListPaginationState_Tags["Idle"] = "Idle";
  SpaceRoomListPaginationState_Tags["Loading"] = "Loading";
})(SpaceRoomListPaginationState_Tags || (SpaceRoomListPaginationState_Tags = {}));
export var SpaceRoomListPaginationState = function () {
  var Idle_ = /*#__PURE__*/function (_UniffiEnum) {
    function Idle_(inner) {
      var _this;
      _classCallCheck(this, Idle_);
      _this = _callSuper(this, Idle_, ["SpaceRoomListPaginationState", "Idle"]);
      /**
       * @private
       * This field is private and should not be used, use `tag` instead.
       */
      _defineProperty(_this, uniffiTypeNameSymbol, "SpaceRoomListPaginationState");
      _defineProperty(_this, "tag", SpaceRoomListPaginationState_Tags.Idle);
      _defineProperty(_this, "inner", void 0);
      _this.inner = Object.freeze(inner);
      return _this;
    }
    _inherits(Idle_, _UniffiEnum);
    return _createClass(Idle_, null, [{
      key: "new",
      value: function _new(inner) {
        return new Idle_(inner);
      }
    }, {
      key: "instanceOf",
      value: function instanceOf(obj) {
        return obj.tag === SpaceRoomListPaginationState_Tags.Idle;
      }
    }]);
  }(UniffiEnum);
  var Loading_ = /*#__PURE__*/function (_UniffiEnum2) {
    function Loading_() {
      var _this2;
      _classCallCheck(this, Loading_);
      _this2 = _callSuper(this, Loading_, ["SpaceRoomListPaginationState", "Loading"]);
      /**
       * @private
       * This field is private and should not be used, use `tag` instead.
       */
      _defineProperty(_this2, uniffiTypeNameSymbol, "SpaceRoomListPaginationState");
      _defineProperty(_this2, "tag", SpaceRoomListPaginationState_Tags.Loading);
      return _this2;
    }
    _inherits(Loading_, _UniffiEnum2);
    return _createClass(Loading_, null, [{
      key: "new",
      value: function _new() {
        return new Loading_();
      }
    }, {
      key: "instanceOf",
      value: function instanceOf(obj) {
        return obj.tag === SpaceRoomListPaginationState_Tags.Loading;
      }
    }]);
  }(UniffiEnum);
  function instanceOf(obj) {
    return obj[uniffiTypeNameSymbol] === "SpaceRoomListPaginationState";
  }
  return Object.freeze({
    instanceOf: instanceOf,
    Idle: Idle_,
    Loading: Loading_
  });
}();
// FfiConverter for enum SpaceRoomListPaginationState
var FfiConverterTypeSpaceRoomListPaginationState = function () {
  var ordinalConverter = FfiConverterInt32;
  var FFIConverter = /*#__PURE__*/function (_AbstractFfiConverter3) {
    function FFIConverter() {
      _classCallCheck(this, FFIConverter);
      return _callSuper(this, FFIConverter, arguments);
    }
    _inherits(FFIConverter, _AbstractFfiConverter3);
    return _createClass(FFIConverter, [{
      key: "read",
      value: function read(from) {
        switch (ordinalConverter.read(from)) {
          case 1:
            return new SpaceRoomListPaginationState.Idle({
              endReached: FfiConverterBool.read(from)
            });
          case 2:
            return new SpaceRoomListPaginationState.Loading();
          default:
            throw new UniffiInternalError.UnexpectedEnumCase();
        }
      }
    }, {
      key: "write",
      value: function write(value, into) {
        switch (value.tag) {
          case SpaceRoomListPaginationState_Tags.Idle:
            {
              ordinalConverter.write(1, into);
              var inner = value.inner;
              FfiConverterBool.write(inner.endReached, into);
              return;
            }
          case SpaceRoomListPaginationState_Tags.Loading:
            {
              ordinalConverter.write(2, into);
              return;
            }
          default:
            // Throwing from here means that SpaceRoomListPaginationState_Tags hasn't matched an ordinal.
            throw new UniffiInternalError.UnexpectedEnumCase();
        }
      }
    }, {
      key: "allocationSize",
      value: function allocationSize(value) {
        switch (value.tag) {
          case SpaceRoomListPaginationState_Tags.Idle:
            {
              var inner = value.inner;
              var size = ordinalConverter.allocationSize(1);
              size += FfiConverterBool.allocationSize(inner.endReached);
              return size;
            }
          case SpaceRoomListPaginationState_Tags.Loading:
            {
              return ordinalConverter.allocationSize(2);
            }
          default:
            throw new UniffiInternalError.UnexpectedEnumCase();
        }
      }
    }]);
  }(AbstractFfiConverterByteArray);
  return new FFIConverter();
}();
/**
 * This should be called before anything else.
 *
 * It is likely that this is being done for you by the library's `index.ts`.
 *
 * It checks versions of uniffi between when the Rust scaffolding was generated
 * and when the bindings were generated.
 *
 * It also initializes the machinery to enable Rust to talk back to Javascript.
 */
function uniffiEnsureInitialized() {
  // Get the bindings contract version from our ComponentInterface
  var bindingsContractVersion = 29;
  // Get the scaffolding contract version by calling the into the dylib
  var scaffoldingContractVersion = nativeModule().ubrn_ffi_matrix_sdk_ui_uniffi_contract_version();
  if (bindingsContractVersion !== scaffoldingContractVersion) {
    throw new UniffiInternalError.ContractVersionMismatch(scaffoldingContractVersion, bindingsContractVersion);
  }
}
export default Object.freeze({
  initialize: uniffiEnsureInitialized,
  converters: {
    FfiConverterTypeEventItemOrigin: FfiConverterTypeEventItemOrigin,
    FfiConverterTypeRoomPinnedEventsChange: FfiConverterTypeRoomPinnedEventsChange,
    FfiConverterTypeSpaceRoomListPaginationState: FfiConverterTypeSpaceRoomListPaginationState
  }
});