var _process;
function _classCallCheck(a, n) { if (!(a instanceof n)) throw new TypeError("Cannot call a class as a function"); }
function _defineProperties(e, r) { for (var t = 0; t < r.length; t++) { var o = r[t]; o.enumerable = o.enumerable || !1, o.configurable = !0, "value" in o && (o.writable = !0), Object.defineProperty(e, _toPropertyKey(o.key), o); } }
function _createClass(e, r, t) { return r && _defineProperties(e.prototype, r), t && _defineProperties(e, t), Object.defineProperty(e, "prototype", { writable: !1 }), e; }
function _toPropertyKey(t) { var i = _toPrimitive(t, "string"); return "symbol" == _typeof(i) ? i : i + ""; }
function _toPrimitive(t, r) { if ("object" != _typeof(t) || !t) return t; var e = t[Symbol.toPrimitive]; if (void 0 !== e) { var i = e.call(t, r || "default"); if ("object" != _typeof(i)) return i; throw new TypeError("@@toPrimitive must return a primitive value."); } return ("string" === r ? String : Number)(t); }
function _callSuper(t, o, e) { return o = _getPrototypeOf(o), _possibleConstructorReturn(t, _isNativeReflectConstruct() ? Reflect.construct(o, e || [], _getPrototypeOf(t).constructor) : o.apply(t, e)); }
function _possibleConstructorReturn(t, e) { if (e && ("object" == _typeof(e) || "function" == typeof e)) return e; if (void 0 !== e) throw new TypeError("Derived constructors may only return object or undefined"); return _assertThisInitialized(t); }
function _assertThisInitialized(e) { if (void 0 === e) throw new ReferenceError("this hasn't been initialised - super() hasn't been called"); return e; }
function _isNativeReflectConstruct() { try { var t = !Boolean.prototype.valueOf.call(Reflect.construct(Boolean, [], function () {})); } catch (t) {} return (_isNativeReflectConstruct = function _isNativeReflectConstruct() { return !!t; })(); }
function _getPrototypeOf(t) { return _getPrototypeOf = Object.setPrototypeOf ? Object.getPrototypeOf.bind() : function (t) { return t.__proto__ || Object.getPrototypeOf(t); }, _getPrototypeOf(t); }
function _inherits(t, e) { if ("function" != typeof e && null !== e) throw new TypeError("Super expression must either be null or a function"); t.prototype = Object.create(e && e.prototype, { constructor: { value: t, writable: !0, configurable: !0 } }), Object.defineProperty(t, "prototype", { writable: !1 }), e && _setPrototypeOf(t, e); }
function _setPrototypeOf(t, e) { return _setPrototypeOf = Object.setPrototypeOf ? Object.setPrototypeOf.bind() : function (t, e) { return t.__proto__ = e, t; }, _setPrototypeOf(t, e); }
function _typeof(o) { "@babel/helpers - typeof"; return _typeof = "function" == typeof Symbol && "symbol" == typeof Symbol.iterator ? function (o) { return typeof o; } : function (o) { return o && "function" == typeof Symbol && o.constructor === Symbol && o !== Symbol.prototype ? "symbol" : typeof o; }, _typeof(o); }
// This file was autogenerated by some hot garbage in the `uniffi-bindgen-react-native` crate.
// Trust me, you don't want to mess with it!
/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
import * as wasmBundle from "./wasm-bindgen/index.js";
import { AbstractFfiConverterByteArray, FfiConverterDuration, FfiConverterInt32, FfiConverterOptional, FfiConverterUInt64, UniffiInternalError, UniffiRustCaller, uniffiCreateFfiConverterString, uniffiCreateRecord } from "uniffi-bindgen-react-native";
// Get converters from the other files, if any.
var nativeModule = function nativeModule() {
  return wasmBundle;
};
var uniffiCaller = new UniffiRustCaller(function () {
  return new wasmBundle.RustCallStatus();
});
var uniffiIsDebug =
// @ts-ignore -- The process global might not be defined
(typeof process === "undefined" ? "undefined" : _typeof(process)) !== "object" ||
// @ts-ignore -- The process global might not be defined
((_process = process) === null || _process === void 0 || (_process = _process.env) === null || _process === void 0 ? void 0 : _process.NODE_ENV) !== "production" || false;
/**
 * Generated factory for {@link MediaRetentionPolicy} record objects.
 */
export var MediaRetentionPolicy = function () {
  var _defaults = function defaults() {
    return {};
  };
  var create = function () {
    return uniffiCreateRecord(_defaults);
  }();
  return Object.freeze({
    /**
     * Create a frozen instance of {@link MediaRetentionPolicy}, with defaults specified
     * in Rust, in the {@link matrix_sdk_base} crate.
     */
    create: create,
    /**
     * Create a frozen instance of {@link MediaRetentionPolicy}, with defaults specified
     * in Rust, in the {@link matrix_sdk_base} crate.
     */
    "new": create,
    /**
     * Defaults specified in the {@link matrix_sdk_base} crate.
     */
    defaults: function defaults() {
      return Object.freeze(_defaults());
    }
  });
}();
var FfiConverterTypeMediaRetentionPolicy = function () {
  var FFIConverter = /*#__PURE__*/function (_AbstractFfiConverter) {
    function FFIConverter() {
      _classCallCheck(this, FFIConverter);
      return _callSuper(this, FFIConverter, arguments);
    }
    _inherits(FFIConverter, _AbstractFfiConverter);
    return _createClass(FFIConverter, [{
      key: "read",
      value: function read(from) {
        return {
          maxCacheSize: FfiConverterOptionalUInt64.read(from),
          maxFileSize: FfiConverterOptionalUInt64.read(from),
          lastAccessExpiry: FfiConverterOptionalDuration.read(from),
          cleanupFrequency: FfiConverterOptionalDuration.read(from)
        };
      }
    }, {
      key: "write",
      value: function write(value, into) {
        FfiConverterOptionalUInt64.write(value.maxCacheSize, into);
        FfiConverterOptionalUInt64.write(value.maxFileSize, into);
        FfiConverterOptionalDuration.write(value.lastAccessExpiry, into);
        FfiConverterOptionalDuration.write(value.cleanupFrequency, into);
      }
    }, {
      key: "allocationSize",
      value: function allocationSize(value) {
        return FfiConverterOptionalUInt64.allocationSize(value.maxCacheSize) + FfiConverterOptionalUInt64.allocationSize(value.maxFileSize) + FfiConverterOptionalDuration.allocationSize(value.lastAccessExpiry) + FfiConverterOptionalDuration.allocationSize(value.cleanupFrequency);
      }
    }]);
  }(AbstractFfiConverterByteArray);
  ;
  return new FFIConverter();
}();
var stringConverter = function () {
  var encoder = new TextEncoder();
  var decoder = new TextDecoder();
  return {
    stringToBytes: function stringToBytes(s) {
      return encoder.encode(s);
    },
    bytesToString: function bytesToString(ab) {
      return decoder.decode(ab);
    },
    stringByteLength: function stringByteLength(s) {
      return encoder.encode(s).byteLength;
    }
  };
}();
var FfiConverterString = uniffiCreateFfiConverterString(stringConverter);
/**
 * Represents the state of a room encryption.
 */
export var EncryptionState;
(function (EncryptionState) {
  /**
   * The room is encrypted.
   */
  EncryptionState[EncryptionState["Encrypted"] = 0] = "Encrypted";
  /**
   * The room is not encrypted.
   */
  EncryptionState[EncryptionState["NotEncrypted"] = 1] = "NotEncrypted";
  /**
   * The state of the room encryption is unknown, probably because the
   * `/sync` did not provide all data needed to decide.
   */
  EncryptionState[EncryptionState["Unknown"] = 2] = "Unknown";
})(EncryptionState || (EncryptionState = {}));
var FfiConverterTypeEncryptionState = function () {
  var ordinalConverter = FfiConverterInt32;
  var FFIConverter = /*#__PURE__*/function (_AbstractFfiConverter2) {
    function FFIConverter() {
      _classCallCheck(this, FFIConverter);
      return _callSuper(this, FFIConverter, arguments);
    }
    _inherits(FFIConverter, _AbstractFfiConverter2);
    return _createClass(FFIConverter, [{
      key: "read",
      value: function read(from) {
        switch (ordinalConverter.read(from)) {
          case 1:
            return EncryptionState.Encrypted;
          case 2:
            return EncryptionState.NotEncrypted;
          case 3:
            return EncryptionState.Unknown;
          default:
            throw new UniffiInternalError.UnexpectedEnumCase();
        }
      }
    }, {
      key: "write",
      value: function write(value, into) {
        switch (value) {
          case EncryptionState.Encrypted:
            return ordinalConverter.write(1, into);
          case EncryptionState.NotEncrypted:
            return ordinalConverter.write(2, into);
          case EncryptionState.Unknown:
            return ordinalConverter.write(3, into);
        }
      }
    }, {
      key: "allocationSize",
      value: function allocationSize(value) {
        return ordinalConverter.allocationSize(0);
      }
    }]);
  }(AbstractFfiConverterByteArray);
  return new FFIConverter();
}();
// FfiConverter for UniffiDuration | undefined
var FfiConverterOptionalDuration = new FfiConverterOptional(FfiConverterDuration);
// FfiConverter for /*u64*/bigint | undefined
var FfiConverterOptionalUInt64 = new FfiConverterOptional(FfiConverterUInt64);
/**
 * This should be called before anything else.
 *
 * It is likely that this is being done for you by the library's `index.ts`.
 *
 * It checks versions of uniffi between when the Rust scaffolding was generated
 * and when the bindings were generated.
 *
 * It also initializes the machinery to enable Rust to talk back to Javascript.
 */
function uniffiEnsureInitialized() {
  // Get the bindings contract version from our ComponentInterface
  var bindingsContractVersion = 29;
  // Get the scaffolding contract version by calling the into the dylib
  var scaffoldingContractVersion = nativeModule().ubrn_ffi_matrix_sdk_base_uniffi_contract_version();
  if (bindingsContractVersion !== scaffoldingContractVersion) {
    throw new UniffiInternalError.ContractVersionMismatch(scaffoldingContractVersion, bindingsContractVersion);
  }
}
export default Object.freeze({
  initialize: uniffiEnsureInitialized,
  converters: {
    FfiConverterTypeEncryptionState: FfiConverterTypeEncryptionState,
    FfiConverterTypeMediaRetentionPolicy: FfiConverterTypeMediaRetentionPolicy
  }
});