var _process;
function _classCallCheck(a, n) { if (!(a instanceof n)) throw new TypeError("Cannot call a class as a function"); }
function _defineProperties(e, r) { for (var t = 0; t < r.length; t++) { var o = r[t]; o.enumerable = o.enumerable || !1, o.configurable = !0, "value" in o && (o.writable = !0), Object.defineProperty(e, _toPropertyKey(o.key), o); } }
function _createClass(e, r, t) { return r && _defineProperties(e.prototype, r), t && _defineProperties(e, t), Object.defineProperty(e, "prototype", { writable: !1 }), e; }
function _toPropertyKey(t) { var i = _toPrimitive(t, "string"); return "symbol" == _typeof(i) ? i : i + ""; }
function _toPrimitive(t, r) { if ("object" != _typeof(t) || !t) return t; var e = t[Symbol.toPrimitive]; if (void 0 !== e) { var i = e.call(t, r || "default"); if ("object" != _typeof(i)) return i; throw new TypeError("@@toPrimitive must return a primitive value."); } return ("string" === r ? String : Number)(t); }
function _callSuper(t, o, e) { return o = _getPrototypeOf(o), _possibleConstructorReturn(t, _isNativeReflectConstruct() ? Reflect.construct(o, e || [], _getPrototypeOf(t).constructor) : o.apply(t, e)); }
function _possibleConstructorReturn(t, e) { if (e && ("object" == _typeof(e) || "function" == typeof e)) return e; if (void 0 !== e) throw new TypeError("Derived constructors may only return object or undefined"); return _assertThisInitialized(t); }
function _assertThisInitialized(e) { if (void 0 === e) throw new ReferenceError("this hasn't been initialised - super() hasn't been called"); return e; }
function _isNativeReflectConstruct() { try { var t = !Boolean.prototype.valueOf.call(Reflect.construct(Boolean, [], function () {})); } catch (t) {} return (_isNativeReflectConstruct = function _isNativeReflectConstruct() { return !!t; })(); }
function _getPrototypeOf(t) { return _getPrototypeOf = Object.setPrototypeOf ? Object.getPrototypeOf.bind() : function (t) { return t.__proto__ || Object.getPrototypeOf(t); }, _getPrototypeOf(t); }
function _inherits(t, e) { if ("function" != typeof e && null !== e) throw new TypeError("Super expression must either be null or a function"); t.prototype = Object.create(e && e.prototype, { constructor: { value: t, writable: !0, configurable: !0 } }), Object.defineProperty(t, "prototype", { writable: !1 }), e && _setPrototypeOf(t, e); }
function _setPrototypeOf(t, e) { return _setPrototypeOf = Object.setPrototypeOf ? Object.setPrototypeOf.bind() : function (t, e) { return t.__proto__ = e, t; }, _setPrototypeOf(t, e); }
function _typeof(o) { "@babel/helpers - typeof"; return _typeof = "function" == typeof Symbol && "symbol" == typeof Symbol.iterator ? function (o) { return typeof o; } : function (o) { return o && "function" == typeof Symbol && o.constructor === Symbol && o !== Symbol.prototype ? "symbol" : typeof o; }, _typeof(o); }
// This file was autogenerated by some hot garbage in the `uniffi-bindgen-react-native` crate.
// Trust me, you don't want to mess with it!
/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
import * as wasmBundle from "./wasm-bindgen/index.js";
import { AbstractFfiConverterByteArray, FfiConverterInt32, UniffiInternalError, UniffiRustCaller, uniffiCreateFfiConverterString } from "uniffi-bindgen-react-native";
// Get converters from the other files, if any.
var nativeModule = function nativeModule() {
  return wasmBundle;
};
var uniffiCaller = new UniffiRustCaller(function () {
  return new wasmBundle.RustCallStatus();
});
var uniffiIsDebug =
// @ts-ignore -- The process global might not be defined
(typeof process === "undefined" ? "undefined" : _typeof(process)) !== "object" ||
// @ts-ignore -- The process global might not be defined
((_process = process) === null || _process === void 0 || (_process = _process.env) === null || _process === void 0 ? void 0 : _process.NODE_ENV) !== "production" || false;
// Public interface members begin here.
var stringConverter = function () {
  var encoder = new TextEncoder();
  var decoder = new TextDecoder();
  return {
    stringToBytes: function stringToBytes(s) {
      return encoder.encode(s);
    },
    bytesToString: function bytesToString(ab) {
      return decoder.decode(ab);
    },
    stringByteLength: function stringByteLength(s) {
      return encoder.encode(s).byteLength;
    }
  };
}();
var FfiConverterString = uniffiCreateFfiConverterString(stringConverter);
/**
 * A machine-readable representation of the authenticity for a `ShieldState`.
 */
export var ShieldStateCode;
(function (ShieldStateCode) {
  /**
   * Not enough information available to check the authenticity.
   */
  ShieldStateCode[ShieldStateCode["AuthenticityNotGuaranteed"] = 0] = "AuthenticityNotGuaranteed";
  /**
   * The sending device isn't yet known by the Client.
   */
  ShieldStateCode[ShieldStateCode["UnknownDevice"] = 1] = "UnknownDevice";
  /**
   * The sending device hasn't been verified by the sender.
   */
  ShieldStateCode[ShieldStateCode["UnsignedDevice"] = 2] = "UnsignedDevice";
  /**
   * The sender hasn't been verified by the Client's user.
   */
  ShieldStateCode[ShieldStateCode["UnverifiedIdentity"] = 3] = "UnverifiedIdentity";
  /**
   * An unencrypted event in an encrypted room.
   */
  ShieldStateCode[ShieldStateCode["SentInClear"] = 4] = "SentInClear";
  /**
   * The sender was previously verified but changed their identity.
   */
  ShieldStateCode[ShieldStateCode["VerificationViolation"] = 5] = "VerificationViolation";
  /**
   * The `sender` field on the event does not match the owner of the device
   * that established the Megolm session.
   */
  ShieldStateCode[ShieldStateCode["MismatchedSender"] = 6] = "MismatchedSender";
})(ShieldStateCode || (ShieldStateCode = {}));
var FfiConverterTypeShieldStateCode = function () {
  var ordinalConverter = FfiConverterInt32;
  var FFIConverter = /*#__PURE__*/function (_AbstractFfiConverter) {
    function FFIConverter() {
      _classCallCheck(this, FFIConverter);
      return _callSuper(this, FFIConverter, arguments);
    }
    _inherits(FFIConverter, _AbstractFfiConverter);
    return _createClass(FFIConverter, [{
      key: "read",
      value: function read(from) {
        switch (ordinalConverter.read(from)) {
          case 1:
            return ShieldStateCode.AuthenticityNotGuaranteed;
          case 2:
            return ShieldStateCode.UnknownDevice;
          case 3:
            return ShieldStateCode.UnsignedDevice;
          case 4:
            return ShieldStateCode.UnverifiedIdentity;
          case 5:
            return ShieldStateCode.SentInClear;
          case 6:
            return ShieldStateCode.VerificationViolation;
          case 7:
            return ShieldStateCode.MismatchedSender;
          default:
            throw new UniffiInternalError.UnexpectedEnumCase();
        }
      }
    }, {
      key: "write",
      value: function write(value, into) {
        switch (value) {
          case ShieldStateCode.AuthenticityNotGuaranteed:
            return ordinalConverter.write(1, into);
          case ShieldStateCode.UnknownDevice:
            return ordinalConverter.write(2, into);
          case ShieldStateCode.UnsignedDevice:
            return ordinalConverter.write(3, into);
          case ShieldStateCode.UnverifiedIdentity:
            return ordinalConverter.write(4, into);
          case ShieldStateCode.SentInClear:
            return ordinalConverter.write(5, into);
          case ShieldStateCode.VerificationViolation:
            return ordinalConverter.write(6, into);
          case ShieldStateCode.MismatchedSender:
            return ordinalConverter.write(7, into);
        }
      }
    }, {
      key: "allocationSize",
      value: function allocationSize(value) {
        return ordinalConverter.allocationSize(0);
      }
    }]);
  }(AbstractFfiConverterByteArray);
  return new FFIConverter();
}();
/**
 * This should be called before anything else.
 *
 * It is likely that this is being done for you by the library's `index.ts`.
 *
 * It checks versions of uniffi between when the Rust scaffolding was generated
 * and when the bindings were generated.
 *
 * It also initializes the machinery to enable Rust to talk back to Javascript.
 */
function uniffiEnsureInitialized() {
  // Get the bindings contract version from our ComponentInterface
  var bindingsContractVersion = 29;
  // Get the scaffolding contract version by calling the into the dylib
  var scaffoldingContractVersion = nativeModule().ubrn_ffi_matrix_sdk_common_uniffi_contract_version();
  if (bindingsContractVersion !== scaffoldingContractVersion) {
    throw new UniffiInternalError.ContractVersionMismatch(scaffoldingContractVersion, bindingsContractVersion);
  }
}
export default Object.freeze({
  initialize: uniffiEnsureInitialized,
  converters: {
    FfiConverterTypeShieldStateCode: FfiConverterTypeShieldStateCode
  }
});