var _process;
function _defineProperty(e, r, t) { return (r = _toPropertyKey(r)) in e ? Object.defineProperty(e, r, { value: t, enumerable: !0, configurable: !0, writable: !0 }) : e[r] = t, e; }
function _classCallCheck(a, n) { if (!(a instanceof n)) throw new TypeError("Cannot call a class as a function"); }
function _defineProperties(e, r) { for (var t = 0; t < r.length; t++) { var o = r[t]; o.enumerable = o.enumerable || !1, o.configurable = !0, "value" in o && (o.writable = !0), Object.defineProperty(e, _toPropertyKey(o.key), o); } }
function _createClass(e, r, t) { return r && _defineProperties(e.prototype, r), t && _defineProperties(e, t), Object.defineProperty(e, "prototype", { writable: !1 }), e; }
function _toPropertyKey(t) { var i = _toPrimitive(t, "string"); return "symbol" == _typeof(i) ? i : i + ""; }
function _toPrimitive(t, r) { if ("object" != _typeof(t) || !t) return t; var e = t[Symbol.toPrimitive]; if (void 0 !== e) { var i = e.call(t, r || "default"); if ("object" != _typeof(i)) return i; throw new TypeError("@@toPrimitive must return a primitive value."); } return ("string" === r ? String : Number)(t); }
function _callSuper(t, o, e) { return o = _getPrototypeOf(o), _possibleConstructorReturn(t, _isNativeReflectConstruct() ? Reflect.construct(o, e || [], _getPrototypeOf(t).constructor) : o.apply(t, e)); }
function _possibleConstructorReturn(t, e) { if (e && ("object" == _typeof(e) || "function" == typeof e)) return e; if (void 0 !== e) throw new TypeError("Derived constructors may only return object or undefined"); return _assertThisInitialized(t); }
function _assertThisInitialized(e) { if (void 0 === e) throw new ReferenceError("this hasn't been initialised - super() hasn't been called"); return e; }
function _isNativeReflectConstruct() { try { var t = !Boolean.prototype.valueOf.call(Reflect.construct(Boolean, [], function () {})); } catch (t) {} return (_isNativeReflectConstruct = function _isNativeReflectConstruct() { return !!t; })(); }
function _getPrototypeOf(t) { return _getPrototypeOf = Object.setPrototypeOf ? Object.getPrototypeOf.bind() : function (t) { return t.__proto__ || Object.getPrototypeOf(t); }, _getPrototypeOf(t); }
function _inherits(t, e) { if ("function" != typeof e && null !== e) throw new TypeError("Super expression must either be null or a function"); t.prototype = Object.create(e && e.prototype, { constructor: { value: t, writable: !0, configurable: !0 } }), Object.defineProperty(t, "prototype", { writable: !1 }), e && _setPrototypeOf(t, e); }
function _setPrototypeOf(t, e) { return _setPrototypeOf = Object.setPrototypeOf ? Object.setPrototypeOf.bind() : function (t, e) { return t.__proto__ = e, t; }, _setPrototypeOf(t, e); }
function _typeof(o) { "@babel/helpers - typeof"; return _typeof = "function" == typeof Symbol && "symbol" == typeof Symbol.iterator ? function (o) { return typeof o; } : function (o) { return o && "function" == typeof Symbol && o.constructor === Symbol && o !== Symbol.prototype ? "symbol" : typeof o; }, _typeof(o); }
// This file was autogenerated by some hot garbage in the `uniffi-bindgen-react-native` crate.
// Trust me, you don't want to mess with it!
/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
import * as wasmBundle from "./wasm-bindgen/index.js";
import { AbstractFfiConverterByteArray, FfiConverterBool, FfiConverterFloat64, FfiConverterInt32, FfiConverterInt64, FfiConverterObject, FfiConverterOptional, UniffiAbstractObject, UniffiEnum, UniffiError, UniffiInternalError, UniffiRustCaller, destructorGuardSymbol, pointerLiteralSymbol, uniffiCreateFfiConverterString, uniffiCreateRecord, uniffiTypeNameSymbol, variantOrdinalSymbol } from "uniffi-bindgen-react-native";
// Get converters from the other files, if any.
var nativeModule = function nativeModule() {
  return wasmBundle;
};
var uniffiCaller = new UniffiRustCaller(function () {
  return new wasmBundle.RustCallStatus();
});
var uniffiIsDebug =
// @ts-ignore -- The process global might not be defined
(typeof process === "undefined" ? "undefined" : _typeof(process)) !== "object" ||
// @ts-ignore -- The process global might not be defined
((_process = process) === null || _process === void 0 || (_process = _process.env) === null || _process === void 0 ? void 0 : _process.NODE_ENV) !== "production" || false;
/**
 * Generated factory for {@link RoomPowerLevelChanges} record objects.
 */
export var RoomPowerLevelChanges = function () {
  var _defaults = function defaults() {
    return {
      ban: undefined,
      invite: undefined,
      kick: undefined,
      redact: undefined,
      eventsDefault: undefined,
      stateDefault: undefined,
      usersDefault: undefined,
      roomName: undefined,
      roomAvatar: undefined,
      roomTopic: undefined,
      spaceChild: undefined
    };
  };
  var create = function () {
    return uniffiCreateRecord(_defaults);
  }();
  return Object.freeze({
    /**
     * Create a frozen instance of {@link RoomPowerLevelChanges}, with defaults specified
     * in Rust, in the {@link matrix_sdk} crate.
     */
    create: create,
    /**
     * Create a frozen instance of {@link RoomPowerLevelChanges}, with defaults specified
     * in Rust, in the {@link matrix_sdk} crate.
     */
    "new": create,
    /**
     * Defaults specified in the {@link matrix_sdk} crate.
     */
    defaults: function defaults() {
      return Object.freeze(_defaults());
    }
  });
}();
var FfiConverterTypeRoomPowerLevelChanges = function () {
  var FFIConverter = /*#__PURE__*/function (_AbstractFfiConverter) {
    function FFIConverter() {
      _classCallCheck(this, FFIConverter);
      return _callSuper(this, FFIConverter, arguments);
    }
    _inherits(FFIConverter, _AbstractFfiConverter);
    return _createClass(FFIConverter, [{
      key: "read",
      value: function read(from) {
        return {
          ban: FfiConverterOptionalInt64.read(from),
          invite: FfiConverterOptionalInt64.read(from),
          kick: FfiConverterOptionalInt64.read(from),
          redact: FfiConverterOptionalInt64.read(from),
          eventsDefault: FfiConverterOptionalInt64.read(from),
          stateDefault: FfiConverterOptionalInt64.read(from),
          usersDefault: FfiConverterOptionalInt64.read(from),
          roomName: FfiConverterOptionalInt64.read(from),
          roomAvatar: FfiConverterOptionalInt64.read(from),
          roomTopic: FfiConverterOptionalInt64.read(from),
          spaceChild: FfiConverterOptionalInt64.read(from)
        };
      }
    }, {
      key: "write",
      value: function write(value, into) {
        FfiConverterOptionalInt64.write(value.ban, into);
        FfiConverterOptionalInt64.write(value.invite, into);
        FfiConverterOptionalInt64.write(value.kick, into);
        FfiConverterOptionalInt64.write(value.redact, into);
        FfiConverterOptionalInt64.write(value.eventsDefault, into);
        FfiConverterOptionalInt64.write(value.stateDefault, into);
        FfiConverterOptionalInt64.write(value.usersDefault, into);
        FfiConverterOptionalInt64.write(value.roomName, into);
        FfiConverterOptionalInt64.write(value.roomAvatar, into);
        FfiConverterOptionalInt64.write(value.roomTopic, into);
        FfiConverterOptionalInt64.write(value.spaceChild, into);
      }
    }, {
      key: "allocationSize",
      value: function allocationSize(value) {
        return FfiConverterOptionalInt64.allocationSize(value.ban) + FfiConverterOptionalInt64.allocationSize(value.invite) + FfiConverterOptionalInt64.allocationSize(value.kick) + FfiConverterOptionalInt64.allocationSize(value.redact) + FfiConverterOptionalInt64.allocationSize(value.eventsDefault) + FfiConverterOptionalInt64.allocationSize(value.stateDefault) + FfiConverterOptionalInt64.allocationSize(value.usersDefault) + FfiConverterOptionalInt64.allocationSize(value.roomName) + FfiConverterOptionalInt64.allocationSize(value.roomAvatar) + FfiConverterOptionalInt64.allocationSize(value.roomTopic) + FfiConverterOptionalInt64.allocationSize(value.spaceChild);
      }
    }]);
  }(AbstractFfiConverterByteArray);
  ;
  return new FFIConverter();
}();
/**
 * Generated factory for {@link ServerVendorInfo} record objects.
 */
export var ServerVendorInfo = function () {
  var _defaults2 = function defaults() {
    return {};
  };
  var create = function () {
    return uniffiCreateRecord(_defaults2);
  }();
  return Object.freeze({
    /**
     * Create a frozen instance of {@link ServerVendorInfo}, with defaults specified
     * in Rust, in the {@link matrix_sdk} crate.
     */
    create: create,
    /**
     * Create a frozen instance of {@link ServerVendorInfo}, with defaults specified
     * in Rust, in the {@link matrix_sdk} crate.
     */
    "new": create,
    /**
     * Defaults specified in the {@link matrix_sdk} crate.
     */
    defaults: function defaults() {
      return Object.freeze(_defaults2());
    }
  });
}();
var FfiConverterTypeServerVendorInfo = function () {
  var FFIConverter = /*#__PURE__*/function (_AbstractFfiConverter2) {
    function FFIConverter() {
      _classCallCheck(this, FFIConverter);
      return _callSuper(this, FFIConverter, arguments);
    }
    _inherits(FFIConverter, _AbstractFfiConverter2);
    return _createClass(FFIConverter, [{
      key: "read",
      value: function read(from) {
        return {
          serverName: FfiConverterString.read(from),
          version: FfiConverterString.read(from)
        };
      }
    }, {
      key: "write",
      value: function write(value, into) {
        FfiConverterString.write(value.serverName, into);
        FfiConverterString.write(value.version, into);
      }
    }, {
      key: "allocationSize",
      value: function allocationSize(value) {
        return FfiConverterString.allocationSize(value.serverName) + FfiConverterString.allocationSize(value.version);
      }
    }]);
  }(AbstractFfiConverterByteArray);
  ;
  return new FFIConverter();
}();
/**
 * Generated factory for {@link VirtualElementCallWidgetConfig} record objects.
 */
export var VirtualElementCallWidgetConfig = function () {
  var _defaults3 = function defaults() {
    return {
      skipLobby: undefined,
      header: undefined,
      hideHeader: undefined,
      preload: undefined,
      appPrompt: undefined,
      confineToRoom: undefined,
      hideScreensharing: undefined,
      controlledAudioDevices: undefined,
      sendNotificationType: undefined
    };
  };
  var create = function () {
    return uniffiCreateRecord(_defaults3);
  }();
  return Object.freeze({
    /**
     * Create a frozen instance of {@link VirtualElementCallWidgetConfig}, with defaults specified
     * in Rust, in the {@link matrix_sdk} crate.
     */
    create: create,
    /**
     * Create a frozen instance of {@link VirtualElementCallWidgetConfig}, with defaults specified
     * in Rust, in the {@link matrix_sdk} crate.
     */
    "new": create,
    /**
     * Defaults specified in the {@link matrix_sdk} crate.
     */
    defaults: function defaults() {
      return Object.freeze(_defaults3());
    }
  });
}();
var FfiConverterTypeVirtualElementCallWidgetConfig = function () {
  var FFIConverter = /*#__PURE__*/function (_AbstractFfiConverter3) {
    function FFIConverter() {
      _classCallCheck(this, FFIConverter);
      return _callSuper(this, FFIConverter, arguments);
    }
    _inherits(FFIConverter, _AbstractFfiConverter3);
    return _createClass(FFIConverter, [{
      key: "read",
      value: function read(from) {
        return {
          intent: FfiConverterOptionalTypeIntent.read(from),
          skipLobby: FfiConverterOptionalBool.read(from),
          header: FfiConverterOptionalTypeHeaderStyle.read(from),
          hideHeader: FfiConverterOptionalBool.read(from),
          preload: FfiConverterOptionalBool.read(from),
          appPrompt: FfiConverterOptionalBool.read(from),
          confineToRoom: FfiConverterOptionalBool.read(from),
          hideScreensharing: FfiConverterOptionalBool.read(from),
          controlledAudioDevices: FfiConverterOptionalBool.read(from),
          sendNotificationType: FfiConverterOptionalTypeNotificationType.read(from)
        };
      }
    }, {
      key: "write",
      value: function write(value, into) {
        FfiConverterOptionalTypeIntent.write(value.intent, into);
        FfiConverterOptionalBool.write(value.skipLobby, into);
        FfiConverterOptionalTypeHeaderStyle.write(value.header, into);
        FfiConverterOptionalBool.write(value.hideHeader, into);
        FfiConverterOptionalBool.write(value.preload, into);
        FfiConverterOptionalBool.write(value.appPrompt, into);
        FfiConverterOptionalBool.write(value.confineToRoom, into);
        FfiConverterOptionalBool.write(value.hideScreensharing, into);
        FfiConverterOptionalBool.write(value.controlledAudioDevices, into);
        FfiConverterOptionalTypeNotificationType.write(value.sendNotificationType, into);
      }
    }, {
      key: "allocationSize",
      value: function allocationSize(value) {
        return FfiConverterOptionalTypeIntent.allocationSize(value.intent) + FfiConverterOptionalBool.allocationSize(value.skipLobby) + FfiConverterOptionalTypeHeaderStyle.allocationSize(value.header) + FfiConverterOptionalBool.allocationSize(value.hideHeader) + FfiConverterOptionalBool.allocationSize(value.preload) + FfiConverterOptionalBool.allocationSize(value.appPrompt) + FfiConverterOptionalBool.allocationSize(value.confineToRoom) + FfiConverterOptionalBool.allocationSize(value.hideScreensharing) + FfiConverterOptionalBool.allocationSize(value.controlledAudioDevices) + FfiConverterOptionalTypeNotificationType.allocationSize(value.sendNotificationType);
      }
    }]);
  }(AbstractFfiConverterByteArray);
  ;
  return new FFIConverter();
}();
/**
 * Generated factory for {@link VirtualElementCallWidgetProperties} record objects.
 */
export var VirtualElementCallWidgetProperties = function () {
  var _defaults4 = function defaults() {
    return {
      parentUrl: undefined,
      fontScale: undefined,
      font: undefined,
      posthogUserId: undefined,
      posthogApiHost: undefined,
      posthogApiKey: undefined,
      rageshakeSubmitUrl: undefined,
      sentryDsn: undefined,
      sentryEnvironment: undefined
    };
  };
  var create = function () {
    return uniffiCreateRecord(_defaults4);
  }();
  return Object.freeze({
    /**
     * Create a frozen instance of {@link VirtualElementCallWidgetProperties}, with defaults specified
     * in Rust, in the {@link matrix_sdk} crate.
     */
    create: create,
    /**
     * Create a frozen instance of {@link VirtualElementCallWidgetProperties}, with defaults specified
     * in Rust, in the {@link matrix_sdk} crate.
     */
    "new": create,
    /**
     * Defaults specified in the {@link matrix_sdk} crate.
     */
    defaults: function defaults() {
      return Object.freeze(_defaults4());
    }
  });
}();
var FfiConverterTypeVirtualElementCallWidgetProperties = function () {
  var FFIConverter = /*#__PURE__*/function (_AbstractFfiConverter4) {
    function FFIConverter() {
      _classCallCheck(this, FFIConverter);
      return _callSuper(this, FFIConverter, arguments);
    }
    _inherits(FFIConverter, _AbstractFfiConverter4);
    return _createClass(FFIConverter, [{
      key: "read",
      value: function read(from) {
        return {
          elementCallUrl: FfiConverterString.read(from),
          widgetId: FfiConverterString.read(from),
          parentUrl: FfiConverterOptionalString.read(from),
          fontScale: FfiConverterOptionalFloat64.read(from),
          font: FfiConverterOptionalString.read(from),
          encryption: FfiConverterTypeEncryptionSystem.read(from),
          posthogUserId: FfiConverterOptionalString.read(from),
          posthogApiHost: FfiConverterOptionalString.read(from),
          posthogApiKey: FfiConverterOptionalString.read(from),
          rageshakeSubmitUrl: FfiConverterOptionalString.read(from),
          sentryDsn: FfiConverterOptionalString.read(from),
          sentryEnvironment: FfiConverterOptionalString.read(from)
        };
      }
    }, {
      key: "write",
      value: function write(value, into) {
        FfiConverterString.write(value.elementCallUrl, into);
        FfiConverterString.write(value.widgetId, into);
        FfiConverterOptionalString.write(value.parentUrl, into);
        FfiConverterOptionalFloat64.write(value.fontScale, into);
        FfiConverterOptionalString.write(value.font, into);
        FfiConverterTypeEncryptionSystem.write(value.encryption, into);
        FfiConverterOptionalString.write(value.posthogUserId, into);
        FfiConverterOptionalString.write(value.posthogApiHost, into);
        FfiConverterOptionalString.write(value.posthogApiKey, into);
        FfiConverterOptionalString.write(value.rageshakeSubmitUrl, into);
        FfiConverterOptionalString.write(value.sentryDsn, into);
        FfiConverterOptionalString.write(value.sentryEnvironment, into);
      }
    }, {
      key: "allocationSize",
      value: function allocationSize(value) {
        return FfiConverterString.allocationSize(value.elementCallUrl) + FfiConverterString.allocationSize(value.widgetId) + FfiConverterOptionalString.allocationSize(value.parentUrl) + FfiConverterOptionalFloat64.allocationSize(value.fontScale) + FfiConverterOptionalString.allocationSize(value.font) + FfiConverterTypeEncryptionSystem.allocationSize(value.encryption) + FfiConverterOptionalString.allocationSize(value.posthogUserId) + FfiConverterOptionalString.allocationSize(value.posthogApiHost) + FfiConverterOptionalString.allocationSize(value.posthogApiKey) + FfiConverterOptionalString.allocationSize(value.rageshakeSubmitUrl) + FfiConverterOptionalString.allocationSize(value.sentryDsn) + FfiConverterOptionalString.allocationSize(value.sentryEnvironment);
      }
    }]);
  }(AbstractFfiConverterByteArray);
  ;
  return new FFIConverter();
}();
var stringConverter = function () {
  var encoder = new TextEncoder();
  var decoder = new TextDecoder();
  return {
    stringToBytes: function stringToBytes(s) {
      return encoder.encode(s);
    },
    bytesToString: function bytesToString(ab) {
      return decoder.decode(ab);
    },
    stringByteLength: function stringByteLength(s) {
      return encoder.encode(s).byteLength;
    }
  };
}();
var FfiConverterString = uniffiCreateFfiConverterString(stringConverter);
/**
 * Settings for end-to-end encryption features.
 */
export var BackupDownloadStrategy;
(function (BackupDownloadStrategy) {
  /**
   * Automatically download all room keys from the backup when the backup
   * recovery key has been received. The backup recovery key can be received
   * in two ways:
   *
   * 1. Received as a `m.secret.send` to-device event, after a successful
   * interactive verification.
   * 2. Imported from secret storage (4S) using the
   * [`SecretStore::import_secrets()`] method.
   *
   * [`SecretStore::import_secrets()`]: crate::encryption::secret_storage::SecretStore::import_secrets
   */
  BackupDownloadStrategy[BackupDownloadStrategy["OneShot"] = 0] = "OneShot";
  /**
   * Attempt to download a single room key if an event fails to be decrypted.
   */
  BackupDownloadStrategy[BackupDownloadStrategy["AfterDecryptionFailure"] = 1] = "AfterDecryptionFailure";
  /**
   * Don't download any room keys automatically. The user can manually
   * download room keys using the [`Backups::download_room_key()`] methods.
   *
   * This is the default option.
   */
  BackupDownloadStrategy[BackupDownloadStrategy["Manual"] = 2] = "Manual";
})(BackupDownloadStrategy || (BackupDownloadStrategy = {}));
var FfiConverterTypeBackupDownloadStrategy = function () {
  var ordinalConverter = FfiConverterInt32;
  var FFIConverter = /*#__PURE__*/function (_AbstractFfiConverter5) {
    function FFIConverter() {
      _classCallCheck(this, FFIConverter);
      return _callSuper(this, FFIConverter, arguments);
    }
    _inherits(FFIConverter, _AbstractFfiConverter5);
    return _createClass(FFIConverter, [{
      key: "read",
      value: function read(from) {
        switch (ordinalConverter.read(from)) {
          case 1:
            return BackupDownloadStrategy.OneShot;
          case 2:
            return BackupDownloadStrategy.AfterDecryptionFailure;
          case 3:
            return BackupDownloadStrategy.Manual;
          default:
            throw new UniffiInternalError.UnexpectedEnumCase();
        }
      }
    }, {
      key: "write",
      value: function write(value, into) {
        switch (value) {
          case BackupDownloadStrategy.OneShot:
            return ordinalConverter.write(1, into);
          case BackupDownloadStrategy.AfterDecryptionFailure:
            return ordinalConverter.write(2, into);
          case BackupDownloadStrategy.Manual:
            return ordinalConverter.write(3, into);
        }
      }
    }, {
      key: "allocationSize",
      value: function allocationSize(value) {
        return ordinalConverter.allocationSize(0);
      }
    }]);
  }(AbstractFfiConverterByteArray);
  return new FFIConverter();
}();
// Enum: EncryptionSystem
export var EncryptionSystem_Tags;
(function (EncryptionSystem_Tags) {
  EncryptionSystem_Tags["Unencrypted"] = "Unencrypted";
  EncryptionSystem_Tags["PerParticipantKeys"] = "PerParticipantKeys";
  EncryptionSystem_Tags["SharedSecret"] = "SharedSecret";
})(EncryptionSystem_Tags || (EncryptionSystem_Tags = {}));
/**
 * Defines if a call is encrypted and which encryption system should be used.
 *
 * This controls the url parameters: `perParticipantE2EE`, `password`.
 */
export var EncryptionSystem = function () {
  /**
   * Equivalent to the element call url parameter: `perParticipantE2EE=false`
   * and no password.
   */
  var Unencrypted_ = /*#__PURE__*/function (_UniffiEnum) {
    function Unencrypted_() {
      var _this;
      _classCallCheck(this, Unencrypted_);
      _this = _callSuper(this, Unencrypted_, ["EncryptionSystem", "Unencrypted"]);
      /**
       * @private
       * This field is private and should not be used, use `tag` instead.
       */
      _defineProperty(_this, uniffiTypeNameSymbol, "EncryptionSystem");
      _defineProperty(_this, "tag", EncryptionSystem_Tags.Unencrypted);
      return _this;
    }
    _inherits(Unencrypted_, _UniffiEnum);
    return _createClass(Unencrypted_, null, [{
      key: "new",
      value: function _new() {
        return new Unencrypted_();
      }
    }, {
      key: "instanceOf",
      value: function instanceOf(obj) {
        return obj.tag === EncryptionSystem_Tags.Unencrypted;
      }
    }]);
  }(UniffiEnum);
  /**
   * Equivalent to the element call url parameters:
   * `perParticipantE2EE=true`
   */
  var PerParticipantKeys_ = /*#__PURE__*/function (_UniffiEnum2) {
    function PerParticipantKeys_() {
      var _this2;
      _classCallCheck(this, PerParticipantKeys_);
      _this2 = _callSuper(this, PerParticipantKeys_, ["EncryptionSystem", "PerParticipantKeys"]);
      /**
       * @private
       * This field is private and should not be used, use `tag` instead.
       */
      _defineProperty(_this2, uniffiTypeNameSymbol, "EncryptionSystem");
      _defineProperty(_this2, "tag", EncryptionSystem_Tags.PerParticipantKeys);
      return _this2;
    }
    _inherits(PerParticipantKeys_, _UniffiEnum2);
    return _createClass(PerParticipantKeys_, null, [{
      key: "new",
      value: function _new() {
        return new PerParticipantKeys_();
      }
    }, {
      key: "instanceOf",
      value: function instanceOf(obj) {
        return obj.tag === EncryptionSystem_Tags.PerParticipantKeys;
      }
    }]);
  }(UniffiEnum);
  /**
   * Equivalent to the element call url parameters:
   * `password={secret}`
   */
  var SharedSecret_ = /*#__PURE__*/function (_UniffiEnum3) {
    function SharedSecret_(inner) {
      var _this3;
      _classCallCheck(this, SharedSecret_);
      _this3 = _callSuper(this, SharedSecret_, ["EncryptionSystem", "SharedSecret"]);
      /**
       * @private
       * This field is private and should not be used, use `tag` instead.
       */
      _defineProperty(_this3, uniffiTypeNameSymbol, "EncryptionSystem");
      _defineProperty(_this3, "tag", EncryptionSystem_Tags.SharedSecret);
      _defineProperty(_this3, "inner", void 0);
      _this3.inner = Object.freeze(inner);
      return _this3;
    }
    _inherits(SharedSecret_, _UniffiEnum3);
    return _createClass(SharedSecret_, null, [{
      key: "new",
      value: function _new(inner) {
        return new SharedSecret_(inner);
      }
    }, {
      key: "instanceOf",
      value: function instanceOf(obj) {
        return obj.tag === EncryptionSystem_Tags.SharedSecret;
      }
    }]);
  }(UniffiEnum);
  function instanceOf(obj) {
    return obj[uniffiTypeNameSymbol] === "EncryptionSystem";
  }
  return Object.freeze({
    instanceOf: instanceOf,
    Unencrypted: Unencrypted_,
    PerParticipantKeys: PerParticipantKeys_,
    SharedSecret: SharedSecret_
  });
}();
// FfiConverter for enum EncryptionSystem
var FfiConverterTypeEncryptionSystem = function () {
  var ordinalConverter = FfiConverterInt32;
  var FFIConverter = /*#__PURE__*/function (_AbstractFfiConverter6) {
    function FFIConverter() {
      _classCallCheck(this, FFIConverter);
      return _callSuper(this, FFIConverter, arguments);
    }
    _inherits(FFIConverter, _AbstractFfiConverter6);
    return _createClass(FFIConverter, [{
      key: "read",
      value: function read(from) {
        switch (ordinalConverter.read(from)) {
          case 1:
            return new EncryptionSystem.Unencrypted();
          case 2:
            return new EncryptionSystem.PerParticipantKeys();
          case 3:
            return new EncryptionSystem.SharedSecret({
              secret: FfiConverterString.read(from)
            });
          default:
            throw new UniffiInternalError.UnexpectedEnumCase();
        }
      }
    }, {
      key: "write",
      value: function write(value, into) {
        switch (value.tag) {
          case EncryptionSystem_Tags.Unencrypted:
            {
              ordinalConverter.write(1, into);
              return;
            }
          case EncryptionSystem_Tags.PerParticipantKeys:
            {
              ordinalConverter.write(2, into);
              return;
            }
          case EncryptionSystem_Tags.SharedSecret:
            {
              ordinalConverter.write(3, into);
              var inner = value.inner;
              FfiConverterString.write(inner.secret, into);
              return;
            }
          default:
            // Throwing from here means that EncryptionSystem_Tags hasn't matched an ordinal.
            throw new UniffiInternalError.UnexpectedEnumCase();
        }
      }
    }, {
      key: "allocationSize",
      value: function allocationSize(value) {
        switch (value.tag) {
          case EncryptionSystem_Tags.Unencrypted:
            {
              return ordinalConverter.allocationSize(1);
            }
          case EncryptionSystem_Tags.PerParticipantKeys:
            {
              return ordinalConverter.allocationSize(2);
            }
          case EncryptionSystem_Tags.SharedSecret:
            {
              var inner = value.inner;
              var size = ordinalConverter.allocationSize(3);
              size += FfiConverterString.allocationSize(inner.secret);
              return size;
            }
          default:
            throw new UniffiInternalError.UnexpectedEnumCase();
        }
      }
    }]);
  }(AbstractFfiConverterByteArray);
  return new FFIConverter();
}();
/**
 * Defines how (if) element-call renders a header.
 */
export var HeaderStyle;
(function (HeaderStyle) {
  /**
   * The normal header with branding.
   */
  HeaderStyle[HeaderStyle["Standard"] = 0] = "Standard";
  /**
   * Render a header with a back button (useful on mobile platforms).
   */
  HeaderStyle[HeaderStyle["AppBar"] = 1] = "AppBar";
  /**
   * No Header (useful for webapps).
   */
  HeaderStyle[HeaderStyle["None"] = 2] = "None";
})(HeaderStyle || (HeaderStyle = {}));
var FfiConverterTypeHeaderStyle = function () {
  var ordinalConverter = FfiConverterInt32;
  var FFIConverter = /*#__PURE__*/function (_AbstractFfiConverter7) {
    function FFIConverter() {
      _classCallCheck(this, FFIConverter);
      return _callSuper(this, FFIConverter, arguments);
    }
    _inherits(FFIConverter, _AbstractFfiConverter7);
    return _createClass(FFIConverter, [{
      key: "read",
      value: function read(from) {
        switch (ordinalConverter.read(from)) {
          case 1:
            return HeaderStyle.Standard;
          case 2:
            return HeaderStyle.AppBar;
          case 3:
            return HeaderStyle.None;
          default:
            throw new UniffiInternalError.UnexpectedEnumCase();
        }
      }
    }, {
      key: "write",
      value: function write(value, into) {
        switch (value) {
          case HeaderStyle.Standard:
            return ordinalConverter.write(1, into);
          case HeaderStyle.AppBar:
            return ordinalConverter.write(2, into);
          case HeaderStyle.None:
            return ordinalConverter.write(3, into);
        }
      }
    }, {
      key: "allocationSize",
      value: function allocationSize(value) {
        return ordinalConverter.allocationSize(0);
      }
    }]);
  }(AbstractFfiConverterByteArray);
  return new FFIConverter();
}();
/**
 * Defines the intent of showing the call.
 *
 * This controls whether to show or skip the lobby.
 */
export var Intent;
(function (Intent) {
  /**
   * The user wants to start a call.
   */
  Intent[Intent["StartCall"] = 0] = "StartCall";
  /**
   * The user wants to join an existing call.
   */
  Intent[Intent["JoinExisting"] = 1] = "JoinExisting";
  /**
   * The user wants to join an existing call that is a "Direct Message" (DM)
   * room.
   */
  Intent[Intent["JoinExistingDm"] = 2] = "JoinExistingDm";
  /**
   * The user wants to start a call in a "Direct Message" (DM) room.
   */
  Intent[Intent["StartCallDm"] = 3] = "StartCallDm";
})(Intent || (Intent = {}));
var FfiConverterTypeIntent = function () {
  var ordinalConverter = FfiConverterInt32;
  var FFIConverter = /*#__PURE__*/function (_AbstractFfiConverter8) {
    function FFIConverter() {
      _classCallCheck(this, FFIConverter);
      return _callSuper(this, FFIConverter, arguments);
    }
    _inherits(FFIConverter, _AbstractFfiConverter8);
    return _createClass(FFIConverter, [{
      key: "read",
      value: function read(from) {
        switch (ordinalConverter.read(from)) {
          case 1:
            return Intent.StartCall;
          case 2:
            return Intent.JoinExisting;
          case 3:
            return Intent.JoinExistingDm;
          case 4:
            return Intent.StartCallDm;
          default:
            throw new UniffiInternalError.UnexpectedEnumCase();
        }
      }
    }, {
      key: "write",
      value: function write(value, into) {
        switch (value) {
          case Intent.StartCall:
            return ordinalConverter.write(1, into);
          case Intent.JoinExisting:
            return ordinalConverter.write(2, into);
          case Intent.JoinExistingDm:
            return ordinalConverter.write(3, into);
          case Intent.StartCallDm:
            return ordinalConverter.write(4, into);
        }
      }
    }, {
      key: "allocationSize",
      value: function allocationSize(value) {
        return ordinalConverter.allocationSize(0);
      }
    }]);
  }(AbstractFfiConverterByteArray);
  return new FFIConverter();
}();
/**
 * Types of call notifications.
 */
export var NotificationType;
(function (NotificationType) {
  /**
   * The receiving client should display a visual notification.
   */
  NotificationType[NotificationType["Notification"] = 0] = "Notification";
  /**
   * The receiving client should ring with an audible sound.
   */
  NotificationType[NotificationType["Ring"] = 1] = "Ring";
})(NotificationType || (NotificationType = {}));
var FfiConverterTypeNotificationType = function () {
  var ordinalConverter = FfiConverterInt32;
  var FFIConverter = /*#__PURE__*/function (_AbstractFfiConverter9) {
    function FFIConverter() {
      _classCallCheck(this, FFIConverter);
      return _callSuper(this, FFIConverter, arguments);
    }
    _inherits(FFIConverter, _AbstractFfiConverter9);
    return _createClass(FFIConverter, [{
      key: "read",
      value: function read(from) {
        switch (ordinalConverter.read(from)) {
          case 1:
            return NotificationType.Notification;
          case 2:
            return NotificationType.Ring;
          default:
            throw new UniffiInternalError.UnexpectedEnumCase();
        }
      }
    }, {
      key: "write",
      value: function write(value, into) {
        switch (value) {
          case NotificationType.Notification:
            return ordinalConverter.write(1, into);
          case NotificationType.Ring:
            return ordinalConverter.write(2, into);
        }
      }
    }, {
      key: "allocationSize",
      value: function allocationSize(value) {
        return ordinalConverter.allocationSize(0);
      }
    }]);
  }(AbstractFfiConverterByteArray);
  return new FFIConverter();
}();
/**
 * Current state of a [`Paginator`].
 */
export var PaginatorState;
(function (PaginatorState) {
  /**
   * The initial state of the paginator.
   */
  PaginatorState[PaginatorState["Initial"] = 0] = "Initial";
  /**
   * The paginator is fetching the target initial event.
   */
  PaginatorState[PaginatorState["FetchingTargetEvent"] = 1] = "FetchingTargetEvent";
  /**
   * The target initial event could be found, zero or more paginations have
   * happened since then, and the paginator is at rest now.
   */
  PaginatorState[PaginatorState["Idle"] = 2] = "Idle";
  /**
   * The paginator is… paginating one direction or another.
   */
  PaginatorState[PaginatorState["Paginating"] = 3] = "Paginating";
})(PaginatorState || (PaginatorState = {}));
var FfiConverterTypePaginatorState = function () {
  var ordinalConverter = FfiConverterInt32;
  var FFIConverter = /*#__PURE__*/function (_AbstractFfiConverter0) {
    function FFIConverter() {
      _classCallCheck(this, FFIConverter);
      return _callSuper(this, FFIConverter, arguments);
    }
    _inherits(FFIConverter, _AbstractFfiConverter0);
    return _createClass(FFIConverter, [{
      key: "read",
      value: function read(from) {
        switch (ordinalConverter.read(from)) {
          case 1:
            return PaginatorState.Initial;
          case 2:
            return PaginatorState.FetchingTargetEvent;
          case 3:
            return PaginatorState.Idle;
          case 4:
            return PaginatorState.Paginating;
          default:
            throw new UniffiInternalError.UnexpectedEnumCase();
        }
      }
    }, {
      key: "write",
      value: function write(value, into) {
        switch (value) {
          case PaginatorState.Initial:
            return ordinalConverter.write(1, into);
          case PaginatorState.FetchingTargetEvent:
            return ordinalConverter.write(2, into);
          case PaginatorState.Idle:
            return ordinalConverter.write(3, into);
          case PaginatorState.Paginating:
            return ordinalConverter.write(4, into);
        }
      }
    }, {
      key: "allocationSize",
      value: function allocationSize(value) {
        return ordinalConverter.allocationSize(0);
      }
    }]);
  }(AbstractFfiConverterByteArray);
  return new FFIConverter();
}();
// Flat error type: QrCodeLoginError
export var QrCodeLoginError_Tags;
(function (QrCodeLoginError_Tags) {
  QrCodeLoginError_Tags["OAuth"] = "OAuth";
  QrCodeLoginError_Tags["LoginFailure"] = "LoginFailure";
  QrCodeLoginError_Tags["UnexpectedMessage"] = "UnexpectedMessage";
  QrCodeLoginError_Tags["SecureChannel"] = "SecureChannel";
  QrCodeLoginError_Tags["NotFound"] = "NotFound";
  QrCodeLoginError_Tags["CrossProcessRefreshLock"] = "CrossProcessRefreshLock";
  QrCodeLoginError_Tags["UserIdDiscovery"] = "UserIdDiscovery";
  QrCodeLoginError_Tags["SessionTokens"] = "SessionTokens";
  QrCodeLoginError_Tags["DeviceKeyUpload"] = "DeviceKeyUpload";
  QrCodeLoginError_Tags["SecretImport"] = "SecretImport";
  QrCodeLoginError_Tags["ServerReset"] = "ServerReset";
})(QrCodeLoginError_Tags || (QrCodeLoginError_Tags = {}));
/**
 * The error type for failures while trying to log in a new device using a QR
 * code.
 */
export var QrCodeLoginError = function () {
  /**
   * An error happened while we were communicating with the OAuth 2.0
   * authorization server.
   */
  var OAuth = /*#__PURE__*/function (_UniffiError) {
    function OAuth(message) {
      var _this4;
      _classCallCheck(this, OAuth);
      _this4 = _callSuper(this, OAuth, ["QrCodeLoginError", "OAuth", message]);
      /**
       * @private
       * This field is private and should not be used.
       */
      _defineProperty(_this4, uniffiTypeNameSymbol, "QrCodeLoginError");
      /**
       * @private
       * This field is private and should not be used.
       */
      _defineProperty(_this4, variantOrdinalSymbol, 1);
      _defineProperty(_this4, "tag", QrCodeLoginError_Tags.OAuth);
      return _this4;
    }
    _inherits(OAuth, _UniffiError);
    return _createClass(OAuth, null, [{
      key: "instanceOf",
      value: function instanceOf(e) {
        return _instanceOf(e) && e[variantOrdinalSymbol] === 1;
      }
    }]);
  }(UniffiError);
  /**
   * The other device has signaled to us that the login has failed.
   */
  var LoginFailure = /*#__PURE__*/function (_UniffiError2) {
    function LoginFailure(message) {
      var _this5;
      _classCallCheck(this, LoginFailure);
      _this5 = _callSuper(this, LoginFailure, ["QrCodeLoginError", "LoginFailure", message]);
      /**
       * @private
       * This field is private and should not be used.
       */
      _defineProperty(_this5, uniffiTypeNameSymbol, "QrCodeLoginError");
      /**
       * @private
       * This field is private and should not be used.
       */
      _defineProperty(_this5, variantOrdinalSymbol, 2);
      _defineProperty(_this5, "tag", QrCodeLoginError_Tags.LoginFailure);
      return _this5;
    }
    _inherits(LoginFailure, _UniffiError2);
    return _createClass(LoginFailure, null, [{
      key: "instanceOf",
      value: function instanceOf(e) {
        return _instanceOf(e) && e[variantOrdinalSymbol] === 2;
      }
    }]);
  }(UniffiError);
  /**
   * An unexpected message was received from the other device.
   */
  var UnexpectedMessage = /*#__PURE__*/function (_UniffiError3) {
    function UnexpectedMessage(message) {
      var _this6;
      _classCallCheck(this, UnexpectedMessage);
      _this6 = _callSuper(this, UnexpectedMessage, ["QrCodeLoginError", "UnexpectedMessage", message]);
      /**
       * @private
       * This field is private and should not be used.
       */
      _defineProperty(_this6, uniffiTypeNameSymbol, "QrCodeLoginError");
      /**
       * @private
       * This field is private and should not be used.
       */
      _defineProperty(_this6, variantOrdinalSymbol, 3);
      _defineProperty(_this6, "tag", QrCodeLoginError_Tags.UnexpectedMessage);
      return _this6;
    }
    _inherits(UnexpectedMessage, _UniffiError3);
    return _createClass(UnexpectedMessage, null, [{
      key: "instanceOf",
      value: function instanceOf(e) {
        return _instanceOf(e) && e[variantOrdinalSymbol] === 3;
      }
    }]);
  }(UniffiError);
  /**
   * An error happened while exchanging messages with the other device.
   */
  var SecureChannel = /*#__PURE__*/function (_UniffiError4) {
    function SecureChannel(message) {
      var _this7;
      _classCallCheck(this, SecureChannel);
      _this7 = _callSuper(this, SecureChannel, ["QrCodeLoginError", "SecureChannel", message]);
      /**
       * @private
       * This field is private and should not be used.
       */
      _defineProperty(_this7, uniffiTypeNameSymbol, "QrCodeLoginError");
      /**
       * @private
       * This field is private and should not be used.
       */
      _defineProperty(_this7, variantOrdinalSymbol, 4);
      _defineProperty(_this7, "tag", QrCodeLoginError_Tags.SecureChannel);
      return _this7;
    }
    _inherits(SecureChannel, _UniffiError4);
    return _createClass(SecureChannel, null, [{
      key: "instanceOf",
      value: function instanceOf(e) {
        return _instanceOf(e) && e[variantOrdinalSymbol] === 4;
      }
    }]);
  }(UniffiError);
  /**
   * The rendezvous session was not found and might have expired.
   */
  var NotFound = /*#__PURE__*/function (_UniffiError5) {
    function NotFound(message) {
      var _this8;
      _classCallCheck(this, NotFound);
      _this8 = _callSuper(this, NotFound, ["QrCodeLoginError", "NotFound", message]);
      /**
       * @private
       * This field is private and should not be used.
       */
      _defineProperty(_this8, uniffiTypeNameSymbol, "QrCodeLoginError");
      /**
       * @private
       * This field is private and should not be used.
       */
      _defineProperty(_this8, variantOrdinalSymbol, 5);
      _defineProperty(_this8, "tag", QrCodeLoginError_Tags.NotFound);
      return _this8;
    }
    _inherits(NotFound, _UniffiError5);
    return _createClass(NotFound, null, [{
      key: "instanceOf",
      value: function instanceOf(e) {
        return _instanceOf(e) && e[variantOrdinalSymbol] === 5;
      }
    }]);
  }(UniffiError);
  /**
   * The cross-process refresh lock failed to be initialized.
   */
  var CrossProcessRefreshLock = /*#__PURE__*/function (_UniffiError6) {
    function CrossProcessRefreshLock(message) {
      var _this9;
      _classCallCheck(this, CrossProcessRefreshLock);
      _this9 = _callSuper(this, CrossProcessRefreshLock, ["QrCodeLoginError", "CrossProcessRefreshLock", message]);
      /**
       * @private
       * This field is private and should not be used.
       */
      _defineProperty(_this9, uniffiTypeNameSymbol, "QrCodeLoginError");
      /**
       * @private
       * This field is private and should not be used.
       */
      _defineProperty(_this9, variantOrdinalSymbol, 6);
      _defineProperty(_this9, "tag", QrCodeLoginError_Tags.CrossProcessRefreshLock);
      return _this9;
    }
    _inherits(CrossProcessRefreshLock, _UniffiError6);
    return _createClass(CrossProcessRefreshLock, null, [{
      key: "instanceOf",
      value: function instanceOf(e) {
        return _instanceOf(e) && e[variantOrdinalSymbol] === 6;
      }
    }]);
  }(UniffiError);
  /**
   * An error happened while we were trying to discover our user and device
   * ID, after we have acquired an access token from the OAuth 2.0
   * authorization server.
   */
  var UserIdDiscovery = /*#__PURE__*/function (_UniffiError7) {
    function UserIdDiscovery(message) {
      var _this0;
      _classCallCheck(this, UserIdDiscovery);
      _this0 = _callSuper(this, UserIdDiscovery, ["QrCodeLoginError", "UserIdDiscovery", message]);
      /**
       * @private
       * This field is private and should not be used.
       */
      _defineProperty(_this0, uniffiTypeNameSymbol, "QrCodeLoginError");
      /**
       * @private
       * This field is private and should not be used.
       */
      _defineProperty(_this0, variantOrdinalSymbol, 7);
      _defineProperty(_this0, "tag", QrCodeLoginError_Tags.UserIdDiscovery);
      return _this0;
    }
    _inherits(UserIdDiscovery, _UniffiError7);
    return _createClass(UserIdDiscovery, null, [{
      key: "instanceOf",
      value: function instanceOf(e) {
        return _instanceOf(e) && e[variantOrdinalSymbol] === 7;
      }
    }]);
  }(UniffiError);
  /**
   * We failed to set the session tokens after we figured out our device and
   * user IDs.
   */
  var SessionTokens = /*#__PURE__*/function (_UniffiError8) {
    function SessionTokens(message) {
      var _this1;
      _classCallCheck(this, SessionTokens);
      _this1 = _callSuper(this, SessionTokens, ["QrCodeLoginError", "SessionTokens", message]);
      /**
       * @private
       * This field is private and should not be used.
       */
      _defineProperty(_this1, uniffiTypeNameSymbol, "QrCodeLoginError");
      /**
       * @private
       * This field is private and should not be used.
       */
      _defineProperty(_this1, variantOrdinalSymbol, 8);
      _defineProperty(_this1, "tag", QrCodeLoginError_Tags.SessionTokens);
      return _this1;
    }
    _inherits(SessionTokens, _UniffiError8);
    return _createClass(SessionTokens, null, [{
      key: "instanceOf",
      value: function instanceOf(e) {
        return _instanceOf(e) && e[variantOrdinalSymbol] === 8;
      }
    }]);
  }(UniffiError);
  /**
   * The device keys failed to be uploaded after we successfully logged in.
   */
  var DeviceKeyUpload = /*#__PURE__*/function (_UniffiError9) {
    function DeviceKeyUpload(message) {
      var _this10;
      _classCallCheck(this, DeviceKeyUpload);
      _this10 = _callSuper(this, DeviceKeyUpload, ["QrCodeLoginError", "DeviceKeyUpload", message]);
      /**
       * @private
       * This field is private and should not be used.
       */
      _defineProperty(_this10, uniffiTypeNameSymbol, "QrCodeLoginError");
      /**
       * @private
       * This field is private and should not be used.
       */
      _defineProperty(_this10, variantOrdinalSymbol, 9);
      _defineProperty(_this10, "tag", QrCodeLoginError_Tags.DeviceKeyUpload);
      return _this10;
    }
    _inherits(DeviceKeyUpload, _UniffiError9);
    return _createClass(DeviceKeyUpload, null, [{
      key: "instanceOf",
      value: function instanceOf(e) {
        return _instanceOf(e) && e[variantOrdinalSymbol] === 9;
      }
    }]);
  }(UniffiError);
  /**
   * The secrets bundle we received from the existing device failed to be
   * imported.
   */
  var SecretImport = /*#__PURE__*/function (_UniffiError0) {
    function SecretImport(message) {
      var _this11;
      _classCallCheck(this, SecretImport);
      _this11 = _callSuper(this, SecretImport, ["QrCodeLoginError", "SecretImport", message]);
      /**
       * @private
       * This field is private and should not be used.
       */
      _defineProperty(_this11, uniffiTypeNameSymbol, "QrCodeLoginError");
      /**
       * @private
       * This field is private and should not be used.
       */
      _defineProperty(_this11, variantOrdinalSymbol, 10);
      _defineProperty(_this11, "tag", QrCodeLoginError_Tags.SecretImport);
      return _this11;
    }
    _inherits(SecretImport, _UniffiError0);
    return _createClass(SecretImport, null, [{
      key: "instanceOf",
      value: function instanceOf(e) {
        return _instanceOf(e) && e[variantOrdinalSymbol] === 10;
      }
    }]);
  }(UniffiError);
  /**
   * The other party told us to use a different homeserver but we failed to
   * reset the server URL.
   */
  var ServerReset = /*#__PURE__*/function (_UniffiError1) {
    function ServerReset(message) {
      var _this12;
      _classCallCheck(this, ServerReset);
      _this12 = _callSuper(this, ServerReset, ["QrCodeLoginError", "ServerReset", message]);
      /**
       * @private
       * This field is private and should not be used.
       */
      _defineProperty(_this12, uniffiTypeNameSymbol, "QrCodeLoginError");
      /**
       * @private
       * This field is private and should not be used.
       */
      _defineProperty(_this12, variantOrdinalSymbol, 11);
      _defineProperty(_this12, "tag", QrCodeLoginError_Tags.ServerReset);
      return _this12;
    }
    _inherits(ServerReset, _UniffiError1);
    return _createClass(ServerReset, null, [{
      key: "instanceOf",
      value: function instanceOf(e) {
        return _instanceOf(e) && e[variantOrdinalSymbol] === 11;
      }
    }]);
  }(UniffiError); // Utility function which does not rely on instanceof.
  function _instanceOf(e) {
    return e[uniffiTypeNameSymbol] === "QrCodeLoginError";
  }
  return {
    OAuth: OAuth,
    LoginFailure: LoginFailure,
    UnexpectedMessage: UnexpectedMessage,
    SecureChannel: SecureChannel,
    NotFound: NotFound,
    CrossProcessRefreshLock: CrossProcessRefreshLock,
    UserIdDiscovery: UserIdDiscovery,
    SessionTokens: SessionTokens,
    DeviceKeyUpload: DeviceKeyUpload,
    SecretImport: SecretImport,
    ServerReset: ServerReset,
    instanceOf: _instanceOf
  };
}();
var FfiConverterTypeQRCodeLoginError = function () {
  var intConverter = FfiConverterInt32;
  var FfiConverter = /*#__PURE__*/function (_AbstractFfiConverter1) {
    function FfiConverter() {
      _classCallCheck(this, FfiConverter);
      return _callSuper(this, FfiConverter, arguments);
    }
    _inherits(FfiConverter, _AbstractFfiConverter1);
    return _createClass(FfiConverter, [{
      key: "read",
      value: function read(from) {
        switch (intConverter.read(from)) {
          case 1:
            return new QrCodeLoginError.OAuth(FfiConverterString.read(from));
          case 2:
            return new QrCodeLoginError.LoginFailure(FfiConverterString.read(from));
          case 3:
            return new QrCodeLoginError.UnexpectedMessage(FfiConverterString.read(from));
          case 4:
            return new QrCodeLoginError.SecureChannel(FfiConverterString.read(from));
          case 5:
            return new QrCodeLoginError.NotFound(FfiConverterString.read(from));
          case 6:
            return new QrCodeLoginError.CrossProcessRefreshLock(FfiConverterString.read(from));
          case 7:
            return new QrCodeLoginError.UserIdDiscovery(FfiConverterString.read(from));
          case 8:
            return new QrCodeLoginError.SessionTokens(FfiConverterString.read(from));
          case 9:
            return new QrCodeLoginError.DeviceKeyUpload(FfiConverterString.read(from));
          case 10:
            return new QrCodeLoginError.SecretImport(FfiConverterString.read(from));
          case 11:
            return new QrCodeLoginError.ServerReset(FfiConverterString.read(from));
          default:
            throw new UniffiInternalError.UnexpectedEnumCase();
        }
      }
    }, {
      key: "write",
      value: function write(value, into) {
        var obj = value;
        var index = obj[variantOrdinalSymbol];
        intConverter.write(index, into);
      }
    }, {
      key: "allocationSize",
      value: function allocationSize(value) {
        return intConverter.allocationSize(0);
      }
    }]);
  }(AbstractFfiConverterByteArray);
  return new FfiConverter();
}();
/**
 * The role of a member in a room.
 */
export var RoomMemberRole;
(function (RoomMemberRole) {
  /**
   * The member is a creator.
   *
   * A creator has an infinite power level and cannot be demoted, so this
   * role is immutable. A room can have several creators.
   *
   * It is available in room versions where
   * `explicitly_privilege_room_creators` in [`AuthorizationRules`] is set to
   * `true`.
   *
   * [`AuthorizationRules`]: ruma::room_version_rules::AuthorizationRules
   */
  RoomMemberRole[RoomMemberRole["Creator"] = 0] = "Creator";
  /**
   * The member is an administrator.
   */
  RoomMemberRole[RoomMemberRole["Administrator"] = 1] = "Administrator";
  /**
   * The member is a moderator.
   */
  RoomMemberRole[RoomMemberRole["Moderator"] = 2] = "Moderator";
  /**
   * The member is a regular user.
   */
  RoomMemberRole[RoomMemberRole["User"] = 3] = "User";
})(RoomMemberRole || (RoomMemberRole = {}));
var FfiConverterTypeRoomMemberRole = function () {
  var ordinalConverter = FfiConverterInt32;
  var FFIConverter = /*#__PURE__*/function (_AbstractFfiConverter10) {
    function FFIConverter() {
      _classCallCheck(this, FFIConverter);
      return _callSuper(this, FFIConverter, arguments);
    }
    _inherits(FFIConverter, _AbstractFfiConverter10);
    return _createClass(FFIConverter, [{
      key: "read",
      value: function read(from) {
        switch (ordinalConverter.read(from)) {
          case 1:
            return RoomMemberRole.Creator;
          case 2:
            return RoomMemberRole.Administrator;
          case 3:
            return RoomMemberRole.Moderator;
          case 4:
            return RoomMemberRole.User;
          default:
            throw new UniffiInternalError.UnexpectedEnumCase();
        }
      }
    }, {
      key: "write",
      value: function write(value, into) {
        switch (value) {
          case RoomMemberRole.Creator:
            return ordinalConverter.write(1, into);
          case RoomMemberRole.Administrator:
            return ordinalConverter.write(2, into);
          case RoomMemberRole.Moderator:
            return ordinalConverter.write(3, into);
          case RoomMemberRole.User:
            return ordinalConverter.write(4, into);
        }
      }
    }, {
      key: "allocationSize",
      value: function allocationSize(value) {
        return ordinalConverter.allocationSize(0);
      }
    }]);
  }(AbstractFfiConverterByteArray);
  return new FFIConverter();
}();
// Enum: RoomPaginationStatus
export var RoomPaginationStatus_Tags;
(function (RoomPaginationStatus_Tags) {
  RoomPaginationStatus_Tags["Idle"] = "Idle";
  RoomPaginationStatus_Tags["Paginating"] = "Paginating";
})(RoomPaginationStatus_Tags || (RoomPaginationStatus_Tags = {}));
/**
 * Status for the back-pagination on a room event cache.
 */
export var RoomPaginationStatus = function () {
  /**
   * No back-pagination is happening right now.
   */
  var Idle_ = /*#__PURE__*/function (_UniffiEnum4) {
    function Idle_(inner) {
      var _this13;
      _classCallCheck(this, Idle_);
      _this13 = _callSuper(this, Idle_, ["RoomPaginationStatus", "Idle"]);
      /**
       * @private
       * This field is private and should not be used, use `tag` instead.
       */
      _defineProperty(_this13, uniffiTypeNameSymbol, "RoomPaginationStatus");
      _defineProperty(_this13, "tag", RoomPaginationStatus_Tags.Idle);
      _defineProperty(_this13, "inner", void 0);
      _this13.inner = Object.freeze(inner);
      return _this13;
    }
    _inherits(Idle_, _UniffiEnum4);
    return _createClass(Idle_, null, [{
      key: "new",
      value: function _new(inner) {
        return new Idle_(inner);
      }
    }, {
      key: "instanceOf",
      value: function instanceOf(obj) {
        return obj.tag === RoomPaginationStatus_Tags.Idle;
      }
    }]);
  }(UniffiEnum);
  /**
   * Back-pagination is already running in the background.
   */
  var Paginating_ = /*#__PURE__*/function (_UniffiEnum5) {
    function Paginating_() {
      var _this14;
      _classCallCheck(this, Paginating_);
      _this14 = _callSuper(this, Paginating_, ["RoomPaginationStatus", "Paginating"]);
      /**
       * @private
       * This field is private and should not be used, use `tag` instead.
       */
      _defineProperty(_this14, uniffiTypeNameSymbol, "RoomPaginationStatus");
      _defineProperty(_this14, "tag", RoomPaginationStatus_Tags.Paginating);
      return _this14;
    }
    _inherits(Paginating_, _UniffiEnum5);
    return _createClass(Paginating_, null, [{
      key: "new",
      value: function _new() {
        return new Paginating_();
      }
    }, {
      key: "instanceOf",
      value: function instanceOf(obj) {
        return obj.tag === RoomPaginationStatus_Tags.Paginating;
      }
    }]);
  }(UniffiEnum);
  function instanceOf(obj) {
    return obj[uniffiTypeNameSymbol] === "RoomPaginationStatus";
  }
  return Object.freeze({
    instanceOf: instanceOf,
    Idle: Idle_,
    Paginating: Paginating_
  });
}();
// FfiConverter for enum RoomPaginationStatus
var FfiConverterTypeRoomPaginationStatus = function () {
  var ordinalConverter = FfiConverterInt32;
  var FFIConverter = /*#__PURE__*/function (_AbstractFfiConverter11) {
    function FFIConverter() {
      _classCallCheck(this, FFIConverter);
      return _callSuper(this, FFIConverter, arguments);
    }
    _inherits(FFIConverter, _AbstractFfiConverter11);
    return _createClass(FFIConverter, [{
      key: "read",
      value: function read(from) {
        switch (ordinalConverter.read(from)) {
          case 1:
            return new RoomPaginationStatus.Idle({
              hitTimelineStart: FfiConverterBool.read(from)
            });
          case 2:
            return new RoomPaginationStatus.Paginating();
          default:
            throw new UniffiInternalError.UnexpectedEnumCase();
        }
      }
    }, {
      key: "write",
      value: function write(value, into) {
        switch (value.tag) {
          case RoomPaginationStatus_Tags.Idle:
            {
              ordinalConverter.write(1, into);
              var inner = value.inner;
              FfiConverterBool.write(inner.hitTimelineStart, into);
              return;
            }
          case RoomPaginationStatus_Tags.Paginating:
            {
              ordinalConverter.write(2, into);
              return;
            }
          default:
            // Throwing from here means that RoomPaginationStatus_Tags hasn't matched an ordinal.
            throw new UniffiInternalError.UnexpectedEnumCase();
        }
      }
    }, {
      key: "allocationSize",
      value: function allocationSize(value) {
        switch (value.tag) {
          case RoomPaginationStatus_Tags.Idle:
            {
              var inner = value.inner;
              var size = ordinalConverter.allocationSize(1);
              size += FfiConverterBool.allocationSize(inner.hitTimelineStart);
              return size;
            }
          case RoomPaginationStatus_Tags.Paginating:
            {
              return ordinalConverter.allocationSize(2);
            }
          default:
            throw new UniffiInternalError.UnexpectedEnumCase();
        }
      }
    }]);
  }(AbstractFfiConverterByteArray);
  return new FFIConverter();
}();
/**
 * The data needed to perform authorization using OAuth 2.0.
 */
export var OAuthAuthorizationData = /*#__PURE__*/function (_UniffiAbstractObject) {
  // No primary constructor declared for this class.
  function OAuthAuthorizationData(pointer) {
    var _this15;
    _classCallCheck(this, OAuthAuthorizationData);
    _this15 = _callSuper(this, OAuthAuthorizationData);
    _defineProperty(_this15, uniffiTypeNameSymbol, "OAuthAuthorizationData");
    _defineProperty(_this15, destructorGuardSymbol, void 0);
    _defineProperty(_this15, pointerLiteralSymbol, void 0);
    _this15[pointerLiteralSymbol] = pointer;
    _this15[destructorGuardSymbol] = uniffiTypeOAuthAuthorizationDataObjectFactory.bless(pointer);
    return _this15;
  }
  /**
   * The login URL to use for authorization.
   */
  _inherits(OAuthAuthorizationData, _UniffiAbstractObject);
  return _createClass(OAuthAuthorizationData, [{
    key: "loginUrl",
    value: function loginUrl() {
      var _this16 = this;
      return FfiConverterString.lift(uniffiCaller.rustCall(/*caller:*/function (callStatus) {
        return nativeModule().ubrn_uniffi_matrix_sdk_fn_method_oauthauthorizationdata_login_url(uniffiTypeOAuthAuthorizationDataObjectFactory.clonePointer(_this16), callStatus);
      }, /*liftString:*/FfiConverterString.lift));
    }
    /**
     * {@inheritDoc uniffi-bindgen-react-native#UniffiAbstractObject.uniffiDestroy}
     */
  }, {
    key: "uniffiDestroy",
    value: function uniffiDestroy() {
      var ptr = this[destructorGuardSymbol];
      if (ptr !== undefined) {
        var pointer = uniffiTypeOAuthAuthorizationDataObjectFactory.pointer(this);
        uniffiTypeOAuthAuthorizationDataObjectFactory.freePointer(pointer);
        uniffiTypeOAuthAuthorizationDataObjectFactory.unbless(ptr);
        delete this[destructorGuardSymbol];
      }
    }
  }], [{
    key: "instanceOf",
    value: function instanceOf(obj) {
      return uniffiTypeOAuthAuthorizationDataObjectFactory.isConcreteType(obj);
    }
  }]);
}(UniffiAbstractObject);
var uniffiTypeOAuthAuthorizationDataObjectFactory = function () {
  /// <reference lib="es2021" />
  var registry = typeof FinalizationRegistry !== 'undefined' ? new FinalizationRegistry(function (heldValue) {
    uniffiTypeOAuthAuthorizationDataObjectFactory.freePointer(heldValue);
  }) : null;
  return {
    create: function create(pointer) {
      var instance = Object.create(OAuthAuthorizationData.prototype);
      instance[pointerLiteralSymbol] = pointer;
      instance[destructorGuardSymbol] = this.bless(pointer);
      instance[uniffiTypeNameSymbol] = "OAuthAuthorizationData";
      return instance;
    },
    bless: function bless(p) {
      var ptr = {
        p: p,
        // make sure this object doesn't get optimized away.
        markDestroyed: function markDestroyed() {
          return undefined;
        }
      };
      if (registry) {
        registry.register(ptr, p, ptr);
      }
      return ptr;
    },
    unbless: function unbless(ptr) {
      if (registry) {
        registry.unregister(ptr);
      }
    },
    pointer: function pointer(obj) {
      if (obj[destructorGuardSymbol] === undefined) {
        throw new UniffiInternalError.UnexpectedNullPointer();
      }
      return obj[pointerLiteralSymbol];
    },
    clonePointer: function clonePointer(obj) {
      var pointer = this.pointer(obj);
      return uniffiCaller.rustCall(/*caller:*/function (callStatus) {
        return nativeModule().ubrn_uniffi_matrix_sdk_fn_clone_oauthauthorizationdata(pointer, callStatus);
      }, /*liftString:*/FfiConverterString.lift);
    },
    freePointer: function freePointer(pointer) {
      uniffiCaller.rustCall(/*caller:*/function (callStatus) {
        return nativeModule().ubrn_uniffi_matrix_sdk_fn_free_oauthauthorizationdata(pointer, callStatus);
      }, /*liftString:*/FfiConverterString.lift);
    },
    isConcreteType: function isConcreteType(obj) {
      return obj[destructorGuardSymbol] && obj[uniffiTypeNameSymbol] === "OAuthAuthorizationData";
    }
  };
}();
// FfiConverter for OAuthAuthorizationDataInterface
var FfiConverterTypeOAuthAuthorizationData = new FfiConverterObject(uniffiTypeOAuthAuthorizationDataObjectFactory);
// FfiConverter for boolean | undefined
var FfiConverterOptionalBool = new FfiConverterOptional(FfiConverterBool);
// FfiConverter for /*f64*/number | undefined
var FfiConverterOptionalFloat64 = new FfiConverterOptional(FfiConverterFloat64);
// FfiConverter for /*i64*/bigint | undefined
var FfiConverterOptionalInt64 = new FfiConverterOptional(FfiConverterInt64);
// FfiConverter for string | undefined
var FfiConverterOptionalString = new FfiConverterOptional(FfiConverterString);
// FfiConverter for HeaderStyle | undefined
var FfiConverterOptionalTypeHeaderStyle = new FfiConverterOptional(FfiConverterTypeHeaderStyle);
// FfiConverter for Intent | undefined
var FfiConverterOptionalTypeIntent = new FfiConverterOptional(FfiConverterTypeIntent);
// FfiConverter for NotificationType | undefined
var FfiConverterOptionalTypeNotificationType = new FfiConverterOptional(FfiConverterTypeNotificationType);
/**
 * This should be called before anything else.
 *
 * It is likely that this is being done for you by the library's `index.ts`.
 *
 * It checks versions of uniffi between when the Rust scaffolding was generated
 * and when the bindings were generated.
 *
 * It also initializes the machinery to enable Rust to talk back to Javascript.
 */
function uniffiEnsureInitialized() {
  // Get the bindings contract version from our ComponentInterface
  var bindingsContractVersion = 29;
  // Get the scaffolding contract version by calling the into the dylib
  var scaffoldingContractVersion = nativeModule().ubrn_ffi_matrix_sdk_uniffi_contract_version();
  if (bindingsContractVersion !== scaffoldingContractVersion) {
    throw new UniffiInternalError.ContractVersionMismatch(scaffoldingContractVersion, bindingsContractVersion);
  }
  if (nativeModule().ubrn_uniffi_matrix_sdk_checksum_method_oauthauthorizationdata_login_url() !== 25566) {
    throw new UniffiInternalError.ApiChecksumMismatch("uniffi_matrix_sdk_checksum_method_oauthauthorizationdata_login_url");
  }
}
export default Object.freeze({
  initialize: uniffiEnsureInitialized,
  converters: {
    FfiConverterTypeBackupDownloadStrategy: FfiConverterTypeBackupDownloadStrategy,
    FfiConverterTypeEncryptionSystem: FfiConverterTypeEncryptionSystem,
    FfiConverterTypeHeaderStyle: FfiConverterTypeHeaderStyle,
    FfiConverterTypeIntent: FfiConverterTypeIntent,
    FfiConverterTypeNotificationType: FfiConverterTypeNotificationType,
    FfiConverterTypeOAuthAuthorizationData: FfiConverterTypeOAuthAuthorizationData,
    FfiConverterTypePaginatorState: FfiConverterTypePaginatorState,
    FfiConverterTypeQRCodeLoginError: FfiConverterTypeQRCodeLoginError,
    FfiConverterTypeRoomMemberRole: FfiConverterTypeRoomMemberRole,
    FfiConverterTypeRoomPaginationStatus: FfiConverterTypeRoomPaginationStatus,
    FfiConverterTypeRoomPowerLevelChanges: FfiConverterTypeRoomPowerLevelChanges,
    FfiConverterTypeServerVendorInfo: FfiConverterTypeServerVendorInfo,
    FfiConverterTypeVirtualElementCallWidgetConfig: FfiConverterTypeVirtualElementCallWidgetConfig,
    FfiConverterTypeVirtualElementCallWidgetProperties: FfiConverterTypeVirtualElementCallWidgetProperties
  }
});