"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports["default"] = exports.ShieldStateCode = exports.BackgroundTaskFailureReason_Tags = exports.BackgroundTaskFailureReason = void 0;
var wasmBundle = _interopRequireWildcard(require("./wasm-bindgen/index.js"));
var _uniffiBindgenReactNative = require("uniffi-bindgen-react-native");
var _process;
function _interopRequireWildcard(e, t) { if ("function" == typeof WeakMap) var r = new WeakMap(), n = new WeakMap(); return (_interopRequireWildcard = function _interopRequireWildcard(e, t) { if (!t && e && e.__esModule) return e; var o, i, f = { __proto__: null, "default": e }; if (null === e || "object" != _typeof(e) && "function" != typeof e) return f; if (o = t ? n : r) { if (o.has(e)) return o.get(e); o.set(e, f); } for (var _t in e) "default" !== _t && {}.hasOwnProperty.call(e, _t) && ((i = (o = Object.defineProperty) && Object.getOwnPropertyDescriptor(e, _t)) && (i.get || i.set) ? o(f, _t, i) : f[_t] = e[_t]); return f; })(e, t); }
function _classCallCheck(a, n) { if (!(a instanceof n)) throw new TypeError("Cannot call a class as a function"); }
function _defineProperties(e, r) { for (var t = 0; t < r.length; t++) { var o = r[t]; o.enumerable = o.enumerable || !1, o.configurable = !0, "value" in o && (o.writable = !0), Object.defineProperty(e, _toPropertyKey(o.key), o); } }
function _createClass(e, r, t) { return r && _defineProperties(e.prototype, r), t && _defineProperties(e, t), Object.defineProperty(e, "prototype", { writable: !1 }), e; }
function _callSuper(t, o, e) { return o = _getPrototypeOf(o), _possibleConstructorReturn(t, _isNativeReflectConstruct() ? Reflect.construct(o, e || [], _getPrototypeOf(t).constructor) : o.apply(t, e)); }
function _possibleConstructorReturn(t, e) { if (e && ("object" == _typeof(e) || "function" == typeof e)) return e; if (void 0 !== e) throw new TypeError("Derived constructors may only return object or undefined"); return _assertThisInitialized(t); }
function _assertThisInitialized(e) { if (void 0 === e) throw new ReferenceError("this hasn't been initialised - super() hasn't been called"); return e; }
function _isNativeReflectConstruct() { try { var t = !Boolean.prototype.valueOf.call(Reflect.construct(Boolean, [], function () {})); } catch (t) {} return (_isNativeReflectConstruct = function _isNativeReflectConstruct() { return !!t; })(); }
function _getPrototypeOf(t) { return _getPrototypeOf = Object.setPrototypeOf ? Object.getPrototypeOf.bind() : function (t) { return t.__proto__ || Object.getPrototypeOf(t); }, _getPrototypeOf(t); }
function _inherits(t, e) { if ("function" != typeof e && null !== e) throw new TypeError("Super expression must either be null or a function"); t.prototype = Object.create(e && e.prototype, { constructor: { value: t, writable: !0, configurable: !0 } }), Object.defineProperty(t, "prototype", { writable: !1 }), e && _setPrototypeOf(t, e); }
function _setPrototypeOf(t, e) { return _setPrototypeOf = Object.setPrototypeOf ? Object.setPrototypeOf.bind() : function (t, e) { return t.__proto__ = e, t; }, _setPrototypeOf(t, e); }
function _defineProperty(e, r, t) { return (r = _toPropertyKey(r)) in e ? Object.defineProperty(e, r, { value: t, enumerable: !0, configurable: !0, writable: !0 }) : e[r] = t, e; }
function _toPropertyKey(t) { var i = _toPrimitive(t, "string"); return "symbol" == _typeof(i) ? i : i + ""; }
function _toPrimitive(t, r) { if ("object" != _typeof(t) || !t) return t; var e = t[Symbol.toPrimitive]; if (void 0 !== e) { var i = e.call(t, r || "default"); if ("object" != _typeof(i)) return i; throw new TypeError("@@toPrimitive must return a primitive value."); } return ("string" === r ? String : Number)(t); }
function _typeof(o) { "@babel/helpers - typeof"; return _typeof = "function" == typeof Symbol && "symbol" == typeof Symbol.iterator ? function (o) { return typeof o; } : function (o) { return o && "function" == typeof Symbol && o.constructor === Symbol && o !== Symbol.prototype ? "symbol" : typeof o; }, _typeof(o); } // This file was autogenerated by some hot garbage in the `uniffi-bindgen-react-native` crate.
// Trust me, you don't want to mess with it!
/* tslint:disable */ /* eslint-disable */ // @ts-nocheck
// Get converters from the other files, if any.
var nativeModule = function nativeModule() {
  return wasmBundle;
};
var uniffiCaller = new _uniffiBindgenReactNative.UniffiRustCaller(function () {
  return new wasmBundle.RustCallStatus();
});
var uniffiIsDebug =
// @ts-ignore -- The process global might not be defined
(typeof process === "undefined" ? "undefined" : _typeof(process)) !== "object" ||
// @ts-ignore -- The process global might not be defined
((_process = process) === null || _process === void 0 || (_process = _process.env) === null || _process === void 0 ? void 0 : _process.NODE_ENV) !== "production" || false;
// Public interface members begin here.

var stringConverter = function () {
  var encoder = new TextEncoder();
  var decoder = new TextDecoder();
  return {
    stringToBytes: function stringToBytes(s) {
      return encoder.encode(s);
    },
    bytesToString: function bytesToString(ab) {
      return decoder.decode(ab);
    },
    stringByteLength: function stringByteLength(s) {
      return encoder.encode(s).byteLength;
    }
  };
}();
var FfiConverterString = (0, _uniffiBindgenReactNative.uniffiCreateFfiConverterString)(stringConverter);

// Enum: BackgroundTaskFailureReason
var BackgroundTaskFailureReason_Tags = exports.BackgroundTaskFailureReason_Tags = /*#__PURE__*/function (BackgroundTaskFailureReason_Tags) {
  BackgroundTaskFailureReason_Tags["Panic"] = "Panic";
  BackgroundTaskFailureReason_Tags["Error"] = "Error";
  BackgroundTaskFailureReason_Tags["EarlyTermination"] = "EarlyTermination";
  return BackgroundTaskFailureReason_Tags;
}({});
/**
 * Reason why a background task failed.
 */
var BackgroundTaskFailureReason = exports.BackgroundTaskFailureReason = function () {
  /**
   * The task panicked.
   */
  var Panic_ = /*#__PURE__*/function (_UniffiEnum) {
    function Panic_(inner) {
      var _this;
      _classCallCheck(this, Panic_);
      _this = _callSuper(this, Panic_, ["BackgroundTaskFailureReason", "Panic"]);
      /**
       * @private
       * This field is private and should not be used, use `tag` instead.
       */
      _defineProperty(_this, _uniffiBindgenReactNative.uniffiTypeNameSymbol, "BackgroundTaskFailureReason");
      _defineProperty(_this, "tag", BackgroundTaskFailureReason_Tags.Panic);
      _defineProperty(_this, "inner", void 0);
      _this.inner = Object.freeze(inner);
      return _this;
    }
    _inherits(Panic_, _UniffiEnum);
    return _createClass(Panic_, null, [{
      key: "new",
      value: function _new(inner) {
        return new Panic_(inner);
      }
    }, {
      key: "instanceOf",
      value: function instanceOf(obj) {
        return obj.tag === BackgroundTaskFailureReason_Tags.Panic;
      }
    }]);
  }(_uniffiBindgenReactNative.UniffiEnum);
  /**
   * The task returned an error.
   */
  var Error_ = /*#__PURE__*/function (_UniffiEnum2) {
    function Error_(inner) {
      var _this2;
      _classCallCheck(this, Error_);
      _this2 = _callSuper(this, Error_, ["BackgroundTaskFailureReason", "Error"]);
      /**
       * @private
       * This field is private and should not be used, use `tag` instead.
       */
      _defineProperty(_this2, _uniffiBindgenReactNative.uniffiTypeNameSymbol, "BackgroundTaskFailureReason");
      _defineProperty(_this2, "tag", BackgroundTaskFailureReason_Tags.Error);
      _defineProperty(_this2, "inner", void 0);
      _this2.inner = Object.freeze(inner);
      return _this2;
    }
    _inherits(Error_, _UniffiEnum2);
    return _createClass(Error_, null, [{
      key: "new",
      value: function _new(inner) {
        return new Error_(inner);
      }
    }, {
      key: "instanceOf",
      value: function instanceOf(obj) {
        return obj.tag === BackgroundTaskFailureReason_Tags.Error;
      }
    }]);
  }(_uniffiBindgenReactNative.UniffiEnum);
  /**
   * The task ended unexpectedly (for tasks expected to run forever).
   */
  var EarlyTermination_ = /*#__PURE__*/function (_UniffiEnum3) {
    function EarlyTermination_() {
      var _this3;
      _classCallCheck(this, EarlyTermination_);
      _this3 = _callSuper(this, EarlyTermination_, ["BackgroundTaskFailureReason", "EarlyTermination"]);
      /**
       * @private
       * This field is private and should not be used, use `tag` instead.
       */
      _defineProperty(_this3, _uniffiBindgenReactNative.uniffiTypeNameSymbol, "BackgroundTaskFailureReason");
      _defineProperty(_this3, "tag", BackgroundTaskFailureReason_Tags.EarlyTermination);
      return _this3;
    }
    _inherits(EarlyTermination_, _UniffiEnum3);
    return _createClass(EarlyTermination_, null, [{
      key: "new",
      value: function _new() {
        return new EarlyTermination_();
      }
    }, {
      key: "instanceOf",
      value: function instanceOf(obj) {
        return obj.tag === BackgroundTaskFailureReason_Tags.EarlyTermination;
      }
    }]);
  }(_uniffiBindgenReactNative.UniffiEnum);
  function instanceOf(obj) {
    return obj[_uniffiBindgenReactNative.uniffiTypeNameSymbol] === "BackgroundTaskFailureReason";
  }
  return Object.freeze({
    instanceOf: instanceOf,
    Panic: Panic_,
    Error: Error_,
    EarlyTermination: EarlyTermination_
  });
}();

/**
 * Reason why a background task failed.
 */

// FfiConverter for enum BackgroundTaskFailureReason
var FfiConverterTypeBackgroundTaskFailureReason = function () {
  var ordinalConverter = _uniffiBindgenReactNative.FfiConverterInt32;
  var FFIConverter = /*#__PURE__*/function (_AbstractFfiConverter) {
    function FFIConverter() {
      _classCallCheck(this, FFIConverter);
      return _callSuper(this, FFIConverter, arguments);
    }
    _inherits(FFIConverter, _AbstractFfiConverter);
    return _createClass(FFIConverter, [{
      key: "read",
      value: function read(from) {
        switch (ordinalConverter.read(from)) {
          case 1:
            return new BackgroundTaskFailureReason.Panic({
              message: FfiConverterOptionalString.read(from),
              panicBacktrace: FfiConverterOptionalString.read(from)
            });
          case 2:
            return new BackgroundTaskFailureReason.Error({
              error: FfiConverterString.read(from)
            });
          case 3:
            return new BackgroundTaskFailureReason.EarlyTermination();
          default:
            throw new _uniffiBindgenReactNative.UniffiInternalError.UnexpectedEnumCase();
        }
      }
    }, {
      key: "write",
      value: function write(value, into) {
        switch (value.tag) {
          case BackgroundTaskFailureReason_Tags.Panic:
            {
              ordinalConverter.write(1, into);
              var inner = value.inner;
              FfiConverterOptionalString.write(inner.message, into);
              FfiConverterOptionalString.write(inner.panicBacktrace, into);
              return;
            }
          case BackgroundTaskFailureReason_Tags.Error:
            {
              ordinalConverter.write(2, into);
              var _inner = value.inner;
              FfiConverterString.write(_inner.error, into);
              return;
            }
          case BackgroundTaskFailureReason_Tags.EarlyTermination:
            {
              ordinalConverter.write(3, into);
              return;
            }
          default:
            // Throwing from here means that BackgroundTaskFailureReason_Tags hasn't matched an ordinal.
            throw new _uniffiBindgenReactNative.UniffiInternalError.UnexpectedEnumCase();
        }
      }
    }, {
      key: "allocationSize",
      value: function allocationSize(value) {
        switch (value.tag) {
          case BackgroundTaskFailureReason_Tags.Panic:
            {
              var inner = value.inner;
              var size = ordinalConverter.allocationSize(1);
              size += FfiConverterOptionalString.allocationSize(inner.message);
              size += FfiConverterOptionalString.allocationSize(inner.panicBacktrace);
              return size;
            }
          case BackgroundTaskFailureReason_Tags.Error:
            {
              var _inner2 = value.inner;
              var _size = ordinalConverter.allocationSize(2);
              _size += FfiConverterString.allocationSize(_inner2.error);
              return _size;
            }
          case BackgroundTaskFailureReason_Tags.EarlyTermination:
            {
              return ordinalConverter.allocationSize(3);
            }
          default:
            throw new _uniffiBindgenReactNative.UniffiInternalError.UnexpectedEnumCase();
        }
      }
    }]);
  }(_uniffiBindgenReactNative.AbstractFfiConverterByteArray);
  return new FFIConverter();
}();

/**
 * A machine-readable representation of the authenticity for a `ShieldState`.
 */
var ShieldStateCode = exports.ShieldStateCode = /*#__PURE__*/function (ShieldStateCode) {
  /**
   * Not enough information available to check the authenticity.
   */
  ShieldStateCode[ShieldStateCode["AuthenticityNotGuaranteed"] = 0] = "AuthenticityNotGuaranteed";
  /**
   * The sending device isn't yet known by the Client.
   */
  ShieldStateCode[ShieldStateCode["UnknownDevice"] = 1] = "UnknownDevice";
  /**
   * The sending device hasn't been verified by the sender.
   */
  ShieldStateCode[ShieldStateCode["UnsignedDevice"] = 2] = "UnsignedDevice";
  /**
   * The sender hasn't been verified by the Client's user.
   */
  ShieldStateCode[ShieldStateCode["UnverifiedIdentity"] = 3] = "UnverifiedIdentity";
  /**
   * The sender was previously verified but changed their identity.
   */
  ShieldStateCode[ShieldStateCode["VerificationViolation"] = 4] = "VerificationViolation";
  /**
   * The `sender` field on the event does not match the owner of the device
   * that established the Megolm session.
   */
  ShieldStateCode[ShieldStateCode["MismatchedSender"] = 5] = "MismatchedSender";
  return ShieldStateCode;
}({});
var FfiConverterTypeShieldStateCode = function () {
  var ordinalConverter = _uniffiBindgenReactNative.FfiConverterInt32;
  var FFIConverter = /*#__PURE__*/function (_AbstractFfiConverter2) {
    function FFIConverter() {
      _classCallCheck(this, FFIConverter);
      return _callSuper(this, FFIConverter, arguments);
    }
    _inherits(FFIConverter, _AbstractFfiConverter2);
    return _createClass(FFIConverter, [{
      key: "read",
      value: function read(from) {
        switch (ordinalConverter.read(from)) {
          case 1:
            return ShieldStateCode.AuthenticityNotGuaranteed;
          case 2:
            return ShieldStateCode.UnknownDevice;
          case 3:
            return ShieldStateCode.UnsignedDevice;
          case 4:
            return ShieldStateCode.UnverifiedIdentity;
          case 5:
            return ShieldStateCode.VerificationViolation;
          case 6:
            return ShieldStateCode.MismatchedSender;
          default:
            throw new _uniffiBindgenReactNative.UniffiInternalError.UnexpectedEnumCase();
        }
      }
    }, {
      key: "write",
      value: function write(value, into) {
        switch (value) {
          case ShieldStateCode.AuthenticityNotGuaranteed:
            return ordinalConverter.write(1, into);
          case ShieldStateCode.UnknownDevice:
            return ordinalConverter.write(2, into);
          case ShieldStateCode.UnsignedDevice:
            return ordinalConverter.write(3, into);
          case ShieldStateCode.UnverifiedIdentity:
            return ordinalConverter.write(4, into);
          case ShieldStateCode.VerificationViolation:
            return ordinalConverter.write(5, into);
          case ShieldStateCode.MismatchedSender:
            return ordinalConverter.write(6, into);
        }
      }
    }, {
      key: "allocationSize",
      value: function allocationSize(value) {
        return ordinalConverter.allocationSize(0);
      }
    }]);
  }(_uniffiBindgenReactNative.AbstractFfiConverterByteArray);
  return new FFIConverter();
}();

// FfiConverter for string | undefined
var FfiConverterOptionalString = new _uniffiBindgenReactNative.FfiConverterOptional(FfiConverterString);

/**
 * This should be called before anything else.
 *
 * It is likely that this is being done for you by the library's `index.ts`.
 *
 * It checks versions of uniffi between when the Rust scaffolding was generated
 * and when the bindings were generated.
 *
 * It also initializes the machinery to enable Rust to talk back to Javascript.
 */
function uniffiEnsureInitialized() {
  // Get the bindings contract version from our ComponentInterface
  var bindingsContractVersion = 30;
  // Get the scaffolding contract version by calling the into the dylib
  var scaffoldingContractVersion = nativeModule().ubrn_ffi_matrix_sdk_common_uniffi_contract_version();
  if (bindingsContractVersion !== scaffoldingContractVersion) {
    throw new _uniffiBindgenReactNative.UniffiInternalError.ContractVersionMismatch(scaffoldingContractVersion, bindingsContractVersion);
  }
}
var _default = exports["default"] = Object.freeze({
  initialize: uniffiEnsureInitialized,
  converters: {
    FfiConverterTypeBackgroundTaskFailureReason: FfiConverterTypeBackgroundTaskFailureReason,
    FfiConverterTypeShieldStateCode: FfiConverterTypeShieldStateCode
  }
});