// Generated by uniffi-bindgen-react-native
// Export the generated bindings to the app.
export * from './generated-compat/matrix_sdk';
export * from './generated-compat/matrix_sdk_base';
export * from './generated-compat/matrix_sdk_common';
export * from './generated-compat/matrix_sdk_crypto';
export * from './generated-compat/matrix_sdk_ffi';
export * from './generated-compat/matrix_sdk_ui';
// Now import the bindings so we can:
// - intialize them
// - export them as namespaced objects as the default export.
import * as matrix_sdk from './generated-compat/matrix_sdk';
import * as matrix_sdk_base from './generated-compat/matrix_sdk_base';
import * as matrix_sdk_common from './generated-compat/matrix_sdk_common';
import * as matrix_sdk_crypto from './generated-compat/matrix_sdk_crypto';
import * as matrix_sdk_ffi from './generated-compat/matrix_sdk_ffi';
import * as matrix_sdk_ui from './generated-compat/matrix_sdk_ui';
import initAsync from './generated-compat/wasm-bindgen/index.js';
    import wasmpath from './generated-compat/wasm-bindgen/index_bg';
export async function uniffiInitAsync() {
    await initAsync({ module_or_path: wasmpath });
    // Initialize the generated bindings: mostly checksums, but also callbacks.
    // - the boolean flag ensures this loads exactly once, even if the JS code
    //   is reloaded (e.g. during development with metro).
    matrix_sdk.default.initialize();
    matrix_sdk_base.default.initialize();
    matrix_sdk_common.default.initialize();
    matrix_sdk_crypto.default.initialize();
    matrix_sdk_ffi.default.initialize();
    matrix_sdk_ui.default.initialize();
}
// Export the crates as individually namespaced objects.
export default {
    matrix_sdk,
    matrix_sdk_base,
    matrix_sdk_common,
    matrix_sdk_crypto,
    matrix_sdk_ffi,
    matrix_sdk_ui,
};
